### ISSUE TITLE
Capture additional deployment documentation

### ISSUE THREAD

**Issue by justinribeiro** [GoogleChrome/rendertron#106]
@samuelli I'm going to start capturing some of the offline and ticket conversations around deployment to various providers beyond the GAE environment.

Would you prefer that this be in the readme or should I go about capturing this in the wiki or some other spot?

**Comment by AVGP** [comment]
Do you still have the additional docs? I'd love to see them as part of the README

**Comment by justinribeiro** [comment]
I have more than when I initially talked to Sam about it. :-)

When I get off the road late next week, I'll clearn up some docs and start making PR's.

**Comment by AVGP** [comment]
Awesome, thanks Justin!

**Comment by AVGP** [comment]
Hey Justin, once #316 is merged, we have a bit more infrastructure for this. I'd love to use this issue to fill in `docs/deploy.md` which should become part of the new Github Pages docs for Rendertron :)

Let me know if you have something you can either dump into this issue or wanna take this one yourself. It's [Hacktoberfest](https://hacktoberfest.com) so putting a little more details in here would make this a really good starter issue for someone who's new to OSS (or a good PR for you, if you want that T-Shirt ;))
