### ISSUE TITLE
fullpage screenshot support?

### ISSUE THREAD

**Issue by Nateyo** [GoogleChrome/rendertron#108]
It appears that if you load a page that has more content than the viewport, the rest of the content does not get rendered.  Are there any plans for full page screenshot support?  Am I missing something in the docs?

Thanks.

**Comment by AVGP** [comment]
It's not supported and there are no plans in adding this feature - but pull requests are welcome!
Alternatively, if you are specifically interested in fullpage screenshots, see [this issue on Puppeteer](https://github.com/GoogleChrome/puppeteer/issues/1273)
