### ISSUE TITLE
Rendertron & Websocket (Firebase)

### ISSUE THREAD

**Issue by Oupsla** [GoogleChrome/rendertron#110]
Hello !

I'm really excited about rendertron since his presentation at the polymer summit and I have decided to try it with a personnal project.

But I got a problem with Polymer 2 and Polymerfire to retrieve data from Firebase Database

### Description
Rendertron doesn't work with Polymerfire (https://github.com/firebase/polymerfire)

### Expected outcome
Rendertron render the page and allow websocket to retrieve data

### Actual outcome
No data is transfered through websocket with polymerfire (firebase-query or firebase-document)

### Live Demo
I have set up a github repo with minimal polymer app and polymerfire (and a firebase database with products)

Repo : https://github.com/Oupsla/rendertron-polymerfire
Demo : https://rendertron-polymer.firebaseapp.com

### Steps to reproduce
1. Init Polymer project 
2. Add polymerfire (and in the app import polymerfire/firebase-app.html and polymerfire/firebase-query.html)
3. Retrieve collection of objects from a Firebase Database
4. Polymer serve this app (or deploy it)
5. Rendertron this app

**Comment by samuelli** [comment]
Hey @Oupsla,

Rendertron doesn't automatically detect websocket network activity and hence I suspect the page looks 'ready' to Rendertron.

#126 may help here as it allows you to define explicitly when your page is ready. Do you think you could try that out?

Thanks,
Sam

**Comment by Oupsla** [comment]
Seems to work perfectly 👍
