### ISSUE TITLE
I got ECONNREFUSED error running from `npm start` despite Chrome is running

### ISSUE THREAD

**Issue by RIP21** [GoogleChrome/rendertron#111]
I got ECONNREFUSED error running from `npm start` despite Chrome is running.
```
Uncaught exception
{ Error: connect ECONNREFUSED 127.0.0.1:34876
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 34876 }
```

I tried this one on my local Windows machine (it was fine), and then tried to run it on my DigitalOcean machine, but every time my express server redirects request to the Rendertron (or I request rendering from its UI) I get the error above.
Running Chrome version is:
```
google-chrome -version
Google Chrome 61.0.3163.100
```
The machine is running Ubuntu 16.04.
Maybe some setup hacks for just plain installation? Not dockerized one? Cause there are some instructions in README but for Docker image only, how to apply same fixes for non-dockerized version? Docker is heavy and my tiny machine will not survive its pressure.

Please help :) I really need this stuff :)
BTW, for some reason If I try to redirect renders to the https://render-tron.appspot.com/ instead of my local one (since I couldn't get it up and running) it doesn't render anything saying that it's unable to render URL :( Is it possible to use this endpoint from other IPs or whatever? :)  Cause I have very low demand on site, so this even non-stable instance will be enough for me.

**Comment by hekod777** [comment]
looks like the same problem as my last reply in this post 

https://github.com/GoogleChrome/rendertron/issues/90

if so, it's the problem of chrome launcher.

you can try to either

1. set the pollInterval to 10000 in chrome-launcher.js

or

2. update the chrome-launcher dependency in Rendertron to 0.8.0 (Currently is 0.3.x)


Though I tried both. and still failed. But some people are saying this fixed the problem.

**Comment by RIP21** [comment]
@hekod777 chrome-launcher.js? Where I can find it. He is not in the repo.

**Comment by hekod777** [comment]
Good.

We are now on the same boat.

I posted this issue on chrome-launcher github page 4 days.

Hopefully they can give a fix soon.

PS: if the performance issue of dockerized Rendertron can be fixed, it will be the best. then I don't have to use this npm start work around ~

**Comment by samuelli** [comment]
@RIP21: add your site to https://github.com/GoogleChrome/rendertron/issues/113. It can be used for other sites, but I think I'm seeing some issues with the running instance right now.

**Comment by samuelli** [comment]
It sounds like chrome-launcher only supports some environments and maybe not the DigitalOcean one that you mentioned? The only real dependency is Chrome, so if you have Chrome, maybe we can configure chrome-launcher to point to exactly where it is.

`npm start` should be fine as long as it can find Chrome.

**Comment by RIP21** [comment]
It can find Chrome and it even says in which port it was launched, but then failed to succeed.

**Comment by RIP21** [comment]
@samuelli about my site that was unable to be loaded via your instance, it was a no detection of the page load for some reason.  I fixed that using code that is in the Chrome using stupi 5 second timeout to be sure it loaded :)

**Comment by hekod777** [comment]
the problem of chrome launcher is the debugger

`isDebuggerReady(){}`

you can find more details about this issue here

`https://github.com/GoogleChrome/chrome-launcher/issues/30`

**Comment by hekod777** [comment]
Found something that might help us to get rid of chrome launcher

linke:  https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai

> Creating your own Headless Chrome launcher
> 
> The ChromeHeadless launcher is great because it works out of the box for testing on Headless Chrome. It includes the appropriate Chrome flags for you and launches a remote debugging version of Chrome on port 9222.
> 
> However, sometimes you may want to pass custom flags to Chrome or change the remote debugging port the launcher uses. To do that, create a customLaunchers field that extends the base ChromeHeadless launcher:
> 
> karma.conf.js
> 
> module.exports = function(config) {
>   ...
> 
>   config.set({
>     browsers: ['Chrome', 'ChromeHeadless', 'MyHeadlessChrome'],
> 
>     customLaunchers: {
>       MyHeadlessChrome: {
>         base: 'ChromeHeadless',
>         flags: ['--disable-translate', '--disable-extensions', '--remote-debugging-port=9223']
>       }
>     },
>   }
> };

**Comment by hekod777** [comment]
Actually with the newest version of Rendertron, I am able to run Rendertron on an EC2 instance.

**Comment by samuelli** [comment]
@hekod777: is that without the docker container then?

**Comment by hekod777** [comment]
@samuelli 

Yes, without docker container.

**Comment by andresrl** [comment]
I was having this issue running with npm start and now I solved it.

I've tried the modified version of isDebuggerReady() made in chrome-launcher.js by @hekod777 at https://github.com/GoogleChrome/chrome-launcher/issues/30 and I can see that the Port is being assigned.
Also i have: "chrome-launcher": "^0.8.0",

net.createConnection(this.port) is rejecting the connection. WHY?

Also, I've tried to increase the pollInterval, with no success.

It's a dedicated server with Ubuntu 16.04 and Plesk and Google Chrome 63.0.3239.108

What I did to solve it is to add the '--no-sandbox' to the chromeFlags at main.js, I mean:
`const appPromise = chromeLauncher.launch({`
`chromeFlags: ['--headless', '--disable-gpu', '--remote-debugging-address=0.0.0.0', '--no-sandbox'],`

And solved!!!

**Comment by hekod777** [comment]
@samuelli 

This is something I found regarding this `--no-sandbox` flag

```
It is not a good fix because sandbox is one of the reasons why chrome is one of the safest browser around. No sandbox mode is just a temporary fix and doesn't really solve the problem. It is like a bypass on chrome so troubleshooters can still look more into chrome so they can better assess the situation. 
I suggest solving the main problem that caused your chrome to stop functioning. You can post more about the details of your problem in the forums.
```

As for rendertron, since it's only rendering pages and it's rendering the pages we want it to render, the security concern of `--no-sandbox` shouldn't be a problem right?

**Comment by itmayziii** [comment]
It's not fair to say no sandbox is bad and not provide a solution
