### ISSUE TITLE
Rendertron failed cache AngularJS/Angular 2/4 pages

### ISSUE THREAD

**Issue by hekod777** [GoogleChrome/rendertron#112]
Hi

Rendertron can cache polymer 2.0 apps perfectly fine. But It failed to cached AngularJS or Angular 2/4 pages.

This happens to both npm run and running the --no-cache=false docker container.

## Reproduction Steps

1. modify `/rendertron/src/main.js` by adding the following line below line 107 (`const result = await renderer.serialize(request.params.url, request.query, config);`)

`console.log(result.status);`

2. run rendertron using 'npm start'

3. try to render this site(a polymer 2.0 app) twice

`https://enigmatic-beach-27289.herokuapp.com/`

it will log 200 then 304

4. try to render this site(an AngularJS app) twice

`https://disneycruise.disney.go.com/cruises-destinations/overview/bahamas/`

it will log 200 then 200

--------

# Update

#### 1. Never caches. The response code from Rendertron always gives 200

samples (the second is AngularJS app):

```
https://www.google.com/

https://disneycruise.disney.go.com/cruises-destinations/overview/bermuda/
```

#### 2. The cache is working fine. Rendertron always gives 304 after the first 200

 samples: (the first one is AngularJS app. the second one is Polymer 2.0 App)

```
https://github.com/gothinkster/angularjs-realworld-example-app

https://boiling-tor-88178.herokuapp.com/7
```

for the github repo

- clone the repo

- cd into the folder

- `npm install`

- open src/js/config/app.config.js

- comment in line 12 ` $locationProvider.html5Mode(true);`

- open src/index.html

- add ` <base href="/">` to the head

- run `gulp`

- go to `localhost:4000`

#### 3. Cache works sometimes?

```
https://www.theguardian.com/us

https://www.theguardian.com/us/culture
```

The status code from Rendertron is totally random

It can be something like

200
200
200
304
304
304
200
200
304
200

**Comment by hekod777** [comment]
hmmm....

getting some very interesting results from rendering  the AngularJS page below

`https://www.theguardian.com/us`

the response status code from Rendertron

200
200
200
304
304
304
200
200
304
200

and the speed of 304 response is not much faster than 200 response. sometimes it's even slower. To improve the performance of Rendertron, caching is gonna be a very good area to work on.

**Comment by samuelli** [comment]
304 != cache we want here. The cache we want is the one that saves Rendertron work. 304s here are E-Tag based Express caching, which compares the client-stored browser cache with the full rendered result of Rendertron.

Rendertron's cache is not user-visible. We could potentially add a header to flag this so we can test it better. eg. something like `X-Rendertron-Cached`. The issue here is that your environment can't use the Google Cloud implemented cache.

**Comment by samuelli** [comment]
Closing this issue as the cache was not actually used. Cache for AWS needs to be implemented. A 304-related bug was also fixed in a recent PR.
