### ISSUE TITLE
Where does Rendertron store cache pages? 

### ISSUE THREAD

**Issue by hekod777** [GoogleChrome/rendertron#114]
Hello

Rendertron is using google-cloud/datastore for caching.

I'd like to know where these cached pages are storing.

Thank you!

**Comment by samuelli** [comment]
Hey,

The current cache implementation can only be used with Google Cloud. On Google Cloud, the cache is then backed by the datastore. This was a rather specific design choice over something like redis, which would be faster, but only support a really small number of cached pages.

That being said, its built to be modular, so Rendertron could easily support other caching mechanisms if anyone wanted to implement as such.
