### ISSUE TITLE
ASP.net core middleware for Rendertron

### ISSUE THREAD

**Issue by galamai** [GoogleChrome/rendertron#135]
Hi, I create ASP.net core 2.0 middleware for Rendertron maybe someone will be useful. Repository reference: [https://github.com/galamai/AspNetCore.Rendertron](https://github.com/galamai/AspNetCore.Rendertron).

**Comment by samuelli** [comment]
Nice, would you like me to link it from the Rendertron readme?

**Comment by galamai** [comment]
Yes, of course, if you can. Thank you.
