### ISSUE TITLE
Get HAR output

### ISSUE THREAD

**Issue by ilyaglow** [GoogleChrome/rendertron#139]
Hey there! 

What is your opinion on adding a way to retrieve an HAR formatted output using API?
Something similar what https://github.com/cyrus-and/chrome-har-capturer does.
I think it might be useful to have an ability to debug rendering issues that may happen.

Thank you for your work!

**Comment by samuelli** [comment]
Hi,

Not too familiar with HAR. What is the workflow you're imagining that would make this feature useful? Since headless Chrome is used in Rendertron, it should be fairly easy to debug what is happening there.

Thanks,
Sam

**Comment by ilyaglow** [comment]
HAR will let you inspect the whole webapp's request-response flow while rendering. As a result it gives you useful metrics - for example, how long it took to load a particular image/style/script.

If it's too low level and too specific for rendertron's initial goal of just a PWA rendering solution feel free to close this :)

**Comment by samuelli** [comment]
Yep, I think it'll be fairly simple to spin this off into its own thing. Given that Rendertron is focused on SEO rendering and not performance, I think it'll be better off done separately.

Thanks for the suggestion though!
