### ISSUE TITLE
How to get rendertron to render mobile pages using mobile user agent?

### ISSUE THREAD

**Issue by XavierEr** [GoogleChrome/rendertron#150]

**Comment by XavierEr** [comment]
Refer to #152

**Comment by samuelli** [comment]
Is your server dependent on the user agent string?

**Comment by XavierEr** [comment]
Hi @samuelli . Yup. My server is checking whether is it 'Googlebot' or 'Googlebot Smartphone' user agent string.

**Comment by XavierEr** [comment]
@samuelli Will there be any update on this?

**Comment by samuelli** [comment]
Hi @XavierEr,

I think it would reasonable for Rendertron to be able to switch between a desktop/mobile rendering & a different user agent. A user agent string is meant to represent what the agent is capable of rendering. It's basically similar to the `Accept` header and is why user agent strings have become increasingly complex.

Rendertron is not designed to serve any traffic directly. Instead you will be sniffing the user agent and determining which requests Rendertron should render. Rendertron will then send requests to your server to render the page.

It looks like you'd like to render mobile pages. So the best option I see is that if your server also renders mobile pages on mobile user agents, Rendertron will also be capable of setting a mobile user agent. We can then add a flag that you'll need to set in your middleware to set this mobile flag. How does that sound?

I don't think #152 is the right approach. There's a few reasons: if the agent comes in as "robot" and we know "robot" cannot render, we will send that request through rendertron. If the user agent is passed along as "robot" we'll return to our server. If we're not careful, we'll end up in a loop. Even if we are, we've lost the meaning - we know "robot" doesn't render so we should be serving contents based on that. Instead what we'll really like is for Rendertron to have the mobile Chrome user agent string.

**Comment by XavierEr** [comment]
Hi @samuelli,

I have make some changes to fit in the right approach. Right now it will check for mobile flag from options and if it is set, the predefined mobile user agent will be set.

**Comment by samuelli** [comment]
Fixed in latest version.
