### ISSUE TITLE
Debug mode causes infinite page loading times

### ISSUE THREAD

**Issue by paales** [GoogleChrome/rendertron#151]
I have the following config.json file:

```json
{
  "cache": true,
  "debug": true
}
```

After enabling the debug mode, all pages are loading indefinitely.. I'm having some issues on a certain page for some reason, but I wanted to console.log something, but I'm unable to do so.. It just keeps loading.

It doesn't matter what website I use, it always loads. Starting it with `yarn start`

**Comment by samuelli** [comment]
Thanks for reporting @paales.

**Comment by paales** [comment]
Awesome
