### ISSUE TITLE
google-cloud/datastore issue

### ISSUE THREAD

**Issue by skunk73** [GoogleChrome/rendertron#154]
hello,
getting this when issuing "npm install":

npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'google-cloud/datastore' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'rendertron'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/gian/rendertron
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gian/rendertron/npm-debug.log
npm ERR! not ok code 0

thank you

**Comment by samuelli** [comment]
Hi,

Can you provide more details? https://www.npmjs.com/package/@google-cloud/datastore is in the NPM registry.

I've tried cloning this repository and running npm install, and npm install rendertron.

Thanks,
Sam

**Comment by skunk73** [comment]
that's on a debian 8.10 installation on gcloud.
i've tied on my gentoo desktop and there "npm install" works fine...

on my desktop:
$ npm -v
5.3.0
$ node -v
v8.5.0

while on the vps:
$ npm -v
1.4.21
$ nodejs -v
v0.10.29

so i guess there's a minimum version requirement...

**Comment by AVGP** [comment]
We're not actively supporting node 0.10 anymore. If the issue persists with current versions of node, please reopen :)
