### ISSUE TITLE
Option to force Google to be handled by rendertron as well

### ISSUE THREAD

**Issue by paales** [GoogleChrome/rendertron#157]
We're currently going live with our project, but it seems impossible to solve all the issues in Google Chrome 41. The build systems / Polymer cli have some odd issues that cause render issues (GraphQL queries that are not resolving properly).

So we'd like to use Rendertron to also render pages for Google Bot.

**Comment by hekod777** [comment]
This is what I did.

**Comment by paales** [comment]
Hi @hekod777. Thanks for the suggestion. I've forked prpl server to add this option and now it seems to work. Maybe the prpl server and this rendertron should offer the option to actually SSR it for Google as well..

I'm getting so much odd errors everywhere that I don't know even where to begin to fix stuff. I've mainly got issues with some ES6 libraries that get handled by webpack, but that then are recompiled by the polymer build system or something.. Not sure if that is even a good idea or how to actually solve that, but after spending more than a few days on it, i've given up.

**Comment by samuelli** [comment]
@paales: FYI, I did a write up on Polymer 2 & Googlebot. https://medium.com/dev-channel/polymer-2-and-googlebot-2ad50c5727dd

If you choose to use Rendertron with Googlebot, @hekod777 showed the correct approach here. This depends on what middleware you're using. If you're using `rendertron-middleware` which works `prpl-server`, the options are [documented here](https://github.com/GoogleChrome/rendertron/tree/master/middleware#configuration).

This will configure what you choose to send through to Rendertron. There's no required changes on the Rendertron side here.

**Comment by Enngage** [comment]
Can someone explain why googlebot is excluded from the default set of user agents? I'm really asking out of curiosity because when I use `Fetch` service to see how google crawlers sees my site (Angular 6), it sees just the barebone HTML and does not seem to resolve it.

**Comment by samuelli** [comment]
@Enngage: there's a link to an article in my previous comment. Rendertron is designed to be used with agents that do not render web pages. In the case of googlebot, it does render web pages but with limited capabilities. It's recommended you look at getting your site to render on Googlebot without the need of Rendertron.

**Comment by Enngage** [comment]
Thank you for such a quick response @samuelli .  I thought that the huge advantage of rendetron is that you can get your apps (i.e. the Angular 6, React, vue..) more SEO friendly (instead of relying on the capabilities of web crawlers and the way they handle javascript). 

For example, FireBase seems to promote this as an [awesome](https://angularfirebase.com/lessons/seo-angular-part-1-rendertron-meta-tags/) thing, and thus your comments makes me a bit confused.

Sure, we could use server side rendering (i.e. Angular universal), but thats not always possible or a good option and this where I think Rendertron comes to rescue. Or another way - do you see any reasons why Rendertron **shouldn't** be used for such apps?

**Comment by offirpeer** [comment]
It's the end of 2020 and Googlebot crawler behavior changes every day, one day it crawled our site perfectly(Angular 6+) and in other days it doesn't crawel the website at all.

We added Rendertron to our project and we tested it in several tools such as:
[](https://technicalseo.com/tools/fetch-render/)
[](https://botsimulator.com/)
And even when I change the User Agent in the developer tools to `Google smartphone`  Rendertron returns the prerendered site.

The only problem is when I use the search console or [](https://search.google.com/test/mobile-friendly)
every time I get:
**Page cannot be reached**

Anyone encountered this problem??
