### ISSUE TITLE
About the timeout and pages containing web components

### ISSUE THREAD

**Issue by hekod777** [GoogleChrome/rendertron#162]
One of the problems with rendertron is that if it reaches the time limit, it will send back whatever it has rendered. 

For AngularJS pages, whatever it sends back is normally good enough for bots to do the indexing. 

But for web component pages, it will send back a blank page. Is there a better way to address this issue other than increasing the timeout?

**Comment by samuelli** [comment]
Generally the ideas of progressive enhancement apply here. I would say that ideally the fixes are not on the Rendertron side. eg if it takes too long for Rendertron to render and serialize this is likely indicative of performance problems that your users would be experiencing when they hit your web application.
