### ISSUE TITLE
rendertron middleware vs robot.txt

### ISSUE THREAD

**Issue by hekod777** [GoogleChrome/rendertron#163]
robots.txt file gives instructions about their site to web robots; this is called The Robots Exclusion Protocol.

There are two important considerations when using /robots.txt:

- robots can ignore your /robots.txt. Especially malware robots that scan the web for security vulnerabilities, and email address harvesters used by spammers will pay no attention.
- the /robots.txt file is a publicly available file. Anyone can see what sections of your server you don't want robots to use.

In rendertron middleware, we have `excludeUrlPattern` option. It's a rule that we can total control with and bots have to follow.

Does this mean, in terms of whitelisting, rendertron middleware is more secured than robot.txt?

I'd like to know if there is any other opinions on this robot.txt vs rendertron middleware topic.

Edit 1: Since `excludeUrlPattern` does not prevent bots from crawling and google bots can index the page without the help from rendertron as long as the page is ES5 compatible, `excludeUrlPattern` is not a good way for preventing page being indexed. It seems like `noindex` meta tag is the most reliable way to prevent pages from being indexed?

**Comment by samuelli** [comment]
There is no way to prevent nefarious actors from inspecting the contents of your site. In cases where usage is a question, you can block IP ranges etc. Most search indexers respect /robots.txt. It's up to you how Rendertron fits into your stack - you choose the user agents and urls to use Rendertron with.

I'm not too sure about all the ways to prevent indexing, but definitely rendertron is targeted at only dealing with the rendering of the pages.
