### ISSUE TITLE
Doesn't render my page

### ISSUE THREAD

**Issue by pstreise** [GoogleChrome/rendertron#168]
Hello,

I try to integrate rendertron into our environment. But it returns only a blank page:
https://render-tron.appspot.com/render/https://trusted.de/?wc-inject-shadydom=true

Is the services maybe timing out?

Best Paul!

**Comment by hekod777** [comment]
Tested it on my own instance of rendertron. Got a blank page as well. 

It doesn't seem like a timeout. 

I got the rendering result in less than 10 seconds. No cache was involved.

**Comment by LuisSousaRego** [comment]
I have a similar issue in an Angular project. 
Only content on the index.html file is being rendered.

**Comment by FrancisAguilar21** [comment]
Any updates here? I'm also experiencing the exact same thing.
When I try to use [Facebook's Scrapper](https://developers.facebook.com/tools/debug/og/object/) and check what their scrapper sees and it's blank. :/

**Comment by AVGP** [comment]
Rendertron, as of today, is using Chromium 71. [Support for Custom Elements v1](https://caniuse.com/#feat=custom-elementsv1) and [Shadow DOM v1](https://caniuse.com/#feat=shadowdomv1) first shipped in Chromium 76.

I'll take this issue as an opportunity to update the puppeteer version and thus the Chromium version.

**Comment by AVGP** [comment]
Okay, red herring. As Shadow DOM content is basically inaccessible to Rendertron, it needs to force a "Shady DOM" which isn't helping if there are no polyfills being loaded.

Unfortunately we don't have a better answer to this than: "Load the polyfill for shadow DOM" :/
