### ISSUE TITLE
Doesn't work with ssl

### ISSUE THREAD

**Issue by pablo384** [GoogleChrome/rendertron#169]
this  is the log of rendertron app running and try to render.
`Chrome launched with debugging on port 41152
Listening on port 8080
Cannot render requested URL
{ message: 'net::ERR_NAME_NOT_RESOLVED' }
Cannot render requested URL
{ message: 'net::ERR_NAME_NOT_RESOLVED' }
Cannot render requested URL
{ message: 'net::ERR_NAME_NOT_RESOLVED' }
Cannot render requested URL
{ message: 'net::ERR_NAME_NOT_RESOLVED' }
Cannot render requested URL
{ message: 'net::ERR_NAME_NOT_RESOLVED' }
Cannot render requested URL
{ message: 'net::ERR_NAME_NOT_RESOLVED' }
Cannot render requested URL
{ message: 'net::ERR_NAME_NOT_RESOLVED' }
`

code of deploy:
https://github.com/pablo384/zoo-webapp-deploy
Angular App:
https://github.com/pablo384/Zoo-Front-end

I tried to use rendertron from a VPS in DigitalOcean. the domain is [here](https://pablo384.com/l) so after using https rendertron doesn't work may I did a mistake in the process.

**Comment by pablo384** [comment]
I solved, my nginx config was wrong. I put the domain name and fix it, but I knew thanks a log in prerender.io.
```
upstream pablo384.com {
          server 127.0.0.1:3443;
    }
```
Please close this issue.

**Comment by mariusJar** [comment]
I'm having similar issue, could you provide more details? Your nginx config maybe?
