### ISSUE TITLE
Offer rendertron as a service on Google cloud

### ISSUE THREAD

**Issue by AndreasGalster** [GoogleChrome/rendertron#172]
I know this is unlikely to happen but would be nice to have :). Makes the setup easier if you're not used to using docker.

**Comment by samuelli** [comment]
It's now supported as a service that can be deployed to Google Cloud's Standard environment!

**Comment by cbstodd** [comment]
@samuelli We just deployed and it looks to be costing about $6 a day for our AngularFirebase app. Is this normal?  $180 a month seems really high for a Server Side Rendering feature.
