### ISSUE TITLE
Rendertron with UNCSS Integration

### ISSUE THREAD

**Issue by oleersoy** [GoogleChrome/rendertron#176]
Hi - Just watched the polymer presentation on rendertron and the genius of it is off the hook!  I just posted this question on SO WRT uncss integration and just wanted to place it on rendertron's radar:
https://stackoverflow.com/questions/49440099/using-rendertron-in-conjunction-with-uncss

**Comment by oleersoy** [comment]
Would also be nice to have Angular CLI integration.  So for example `ng build --rendertron` would build out the pages to a rendertron directory or `/dist/rendertron`.

**Comment by AVGP** [comment]
For Angular, I would recommend [Angular Universal](https://angular.io/guide/universal) as an alternative.
