### ISSUE TITLE
super slow rendering speed, need to lower chrome version

### ISSUE THREAD

**Issue by hekod777** [GoogleChrome/rendertron#183]
We just noticed that rendertron's rendering speed is super slow.

Most of the time we will get this message: `10 second time budget limit reached. Attempted rendering: url. Page load event fired: true. Outstanding network requests:1`

and we didn't have this issue back in Jan.

After some debugging, I found that the newest stable version of chrome (66) is causing the issue.

If I downgraded my chrome to 63, the rendering speed is very fast again.

the problem i am having is the command to install chrome@63.0.3239

Someone else is asking too https://stackoverflow.com/questions/49070206/install-specific-version-of-google-chrome-unstable but so far no one could give an answer.

Is there a way to install a specific version of chrome using command line?

PS: It seems that rendertron started having this issue for chrome 64, 65, 66. chrome 63 is fine.

PPS: Since google is not offering the downloads for older version of chrome, we are having difficulty in finding an official chrome 64 `.deb` file.

**Comment by phihochzwei** [comment]
https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

**Comment by samuelli** [comment]
Moved to latest version of Chrome instead.
