### ISSUE TITLE
cache jpgs in folder?

### ISSUE THREAD

**Issue by ford442** [GoogleChrome/rendertron#185]
Hi,
I am trying to get a cached screenshots to automatically save whenever rendertron runs. Can anyone tell me an easy way please? I have tried SVG -> CANVAS -> PNG and also Google Datastore, but both ways seem overly complicated to me.
Is there an obvious point when I could intercept the Base64 string variable into a textarea or .txt perhaps?
I am using shared hosting as well as Google Cloud Compute.
Thanks! Love the script!  :)

**Comment by AVGP** [comment]
Why do you need Rendertron for this? You could use pupeteer directly as well.

But for what it's worth: The `/screenshot/` endpoint returns a JPG right away, so all you need to do is read the response and save it into a file, like this, for example, in node.js:

```javascript
const http = require('http');
const fs = require('fs');

const req = http.request('http://YOUR_RENDERTRON_ADDRESS/screenshot/WHATEVER_URL_YOU_WANT_A_SCREENSHOT_FROM', (res) => {
  res.pipe(fs.createWriteStream('snapshot.jpg'))
});

req.end()
```
