### ISSUE TITLE
Client-side navigation doesn't work

### ISSUE THREAD

**Issue by aslushnikov** [GoogleChrome/rendertron#186]
### Repro steps

1. Take any page of https://pptr.dev, e.g. outline for Puppeteer version 1.5.0: https://pptr.dev/#%3Fproduct=Puppeteer&version=v1.5.0&show=outline
2. Compare [rendertron screenshot](https://render-tron.appspot.com/screenshot/https://pptr.dev/#%3Fproduct=Puppeteer&version=v1.5.0&show=outline?width=2955&height=1549) with [actual result](https://pptr.dev/#%3Fproduct=Puppeteer&version=v1.5.0&show=outline)

The same happens with other SPAs with client-side navigation, e.g. consider rendering https://caniuse.com/#feat=asmjs

### Investigation

Same-document navigation is exposed in devtools protocol via [`Page.navigatedWithinDocument`](https://vanilla.aslushnikov.com/#Page.navigatedWithinDocument) event; this event should be considered to determine page loaded state.

**Comment by samuelli** [comment]
What's the best way to approach this if I'm using `goto()` in puppeteer?

**Comment by aslushnikov** [comment]
@samuelli it should just work!

**Comment by samuelli** [comment]
Ah thanks. This wasn't actually broken but the front page was broken. The # part of the URL was not being sent to the server as that needs to be properly URL encoded.
