### ISSUE TITLE
https://render-tron.appspot.com/ got internal server error

### ISSUE THREAD

**Issue by baranberkay96** [GoogleChrome/rendertron#206]
i tried to take screenshot but got internal server error and this is the link that i want to take screenshot 
[https://www.thesaurus.com/browse/immediately]

**Comment by drupalshift** [comment]
I get this from Avast 
Site Blocked - URL:Phishing

**Comment by baranberkay96** [comment]
i didn't understand which platform you tried in,  could you explain more?

**Comment by AVGP** [comment]
That was a false positive and should no longer be the case. If the issue persists, please reopen the issue.
