### ISSUE TITLE
Googlebot is missing markup

### ISSUE THREAD

**Issue by mpovervliet** [GoogleChrome/rendertron#215]
We've got rendertron setup, but when we fetch our pages as Google in Search console, markup is missing.

Page: https://www.horsecheck.nl/paardrijcap

![search console fetchen als google https www horsecheck nl](https://user-images.githubusercontent.com/10119389/44662153-2a8d4c00-aa0d-11e8-8b99-8e0462d9397b.png)

The missing content is actually in the code, but it's on 1 single line:

![search console fetchen als google https www horsecheck nl 4](https://user-images.githubusercontent.com/10119389/44662294-ac7d7500-aa0d-11e8-880e-6be9c485ce5b.png)
![search console fetchen als google https www horsecheck nl 3](https://user-images.githubusercontent.com/10119389/44662295-ac7d7500-aa0d-11e8-9de8-53dcfe228dad.png)

Any suggestions how to fix this? Any help is much appreciated!

**Comment by mskasal** [comment]
Hi, Middleware has list of bots and Googlebot not one of them. You can use 

```javascript
const botUserAgents = [
        'W3C_Validator',
        'baiduspider',
        'bingbot',
        'embedly',
        'facebookexternalhit',
        'linkedinbot',
        'outbrain',
        'pinterest',
        'quora link preview',
        'rogerbot',
        'showyoubot',
        'slackbot',
        'twitterbot',
        'vkShare',
        'Googlebot',
        'xml-sitemaps'
    ];
app.use(rendertron.makeMiddleware({
    proxyUrl: args['bot-proxy'],
    injectShadyDom: true,
    userAgentPattern: new RegExp(botUserAgents.join('|'), 'i')
}));
```

**Comment by AVGP** [comment]
It seems to be a timeout problem. This page takes way longer than 10 seconds on my stable and fast connection to load.
