### ISSUE TITLE
Injecting a JavaScript object or function? 

### ISSUE THREAD

**Issue by screendriver** [GoogleChrome/rendertron#217]
Hi, 

does `rendertron` inject a JavaScript object or a function or something like this when it renders the page? 

The reason why I'm asking: 

- with that it would be possible to inform the engine when rendering and data fetching is really done. I could call that callback function when I'm certain that my app is ready for caching
- I'm using a CSS-in-JS solution (namely [Glamorous](https://github.com/paypal/glamorous)) that is responsible for styling the app. But because JavaScript will be stripped out from the page, the styles are not applied. The workaround for this is to enable [speedy mode](https://github.com/threepointone/glamor/blob/master/README.md#speedy-mode) but therefore I have to distinguish at runtime if the caller is a real user or `rendertron`

If you look at other solutions like [SEO4Ajax](https://www.seo4ajax.com) (they provide [render hooks](https://www.seo4ajax.com/docs/capture-hooks/)) or [Prerender.io](https://prerender.io) (they provide [window.prerenderReady](https://prerender.io/documentation/test-it)) then you can see what I mean. 

Unfortunately I didn't find anything here in the repository that looks like that.

**Comment by AVGP** [comment]
Rendertron does not provide a JS interface to flag that your app is done rendering at the moment. It sounds like there are other options that support this, tho, so I'm closing this issue.

If you wish to experiment with adding this feature to Rendertron, I'll happily take a look at a PR :)
