### ISSUE TITLE
rendertron don't wait for http request when share link on the facebook or twitter

### ISSUE THREAD

**Issue by elgreatly** [GoogleChrome/rendertron#224]
i'm using rendertron middlelayer node module with angular 6 to pre-render the data to get the actual meta-data 
the problem is when i share the link on the facebook or twitter it don't wait to the http call to get the actual data to add it in meta-data even if the http call just take 100 ms 

but when i run the url directly to the rendertron it get the data correctly without the problem and get the actual meta-data

and if i add the metadata on the component without wait to the http call it works correct

i don't know what the difference, at the end it should call the rendertron url if get from facebook or call the rendertron url directly 

any help will be appreciated

**Comment by elgreatly** [comment]
@hekod777 @samuelli do you have any idea about this issue

**Comment by FrancisAguilar21** [comment]
I'm also experiencing this issue when making calls to a database -- firestore for example. Facebook and Twitter bots instead resort to my fall back meta tags. :(

Any updates on this?

**Comment by nicowagner** [comment]
im having the exact same issue, only googlebot works!

**Comment by AVGP** [comment]
Is there a URL I could use to reproduce the problem? It seems to work fine with a simple demo page that uses JS to generate the meta tags & the demo instance:
<img width="588" alt="_1__Neueste_Tweets___Twitter" src="https://user-images.githubusercontent.com/370246/64538980-f8713280-d360-11e9-8a24-419a078914ea.png">

I guess this might be a timeout problem?

**Comment by elgreatly** [comment]
for me it was a problem in the combination for rendertron URL in the server when i fix it everything working correctly

**Comment by AVGP** [comment]
@elgreatly could you elaborate on that? What was the problem and what exactly fixed it? Did you use a wrong rendertron URL?

**Comment by AVGP** [comment]
Right, thanks for the clarification @elgreatly. Unless someone has steps on how to reproduce the problem, I'll close this soon

**Comment by AVGP** [comment]
Feel free to reopen this issue with more information on how to reproduce this problem.

**Comment by devGitAbhishek** [comment]
Hi,

I have to scrape multiple times the url via share debugger?

I know facebook caches, but i have to scrap multiple times, i am seeing in logs body send via rendertron is updated one but not getting updated in facebook?

Any workaround this?

**Comment by cyber-goka** [comment]
hi, I have the same problem, whenever I share there is no metadata shown. like it's just default, it seems that it is not waiting to finish rendering what can I do?
