### ISSUE TITLE
Can prevent the image loading ?, when a lot of images, the loading speed is very slow

### ISSUE THREAD

**Issue by freehuoshan** [GoogleChrome/rendertron#225]
My site has a lot of images, which makes the crawler response very slow.
can we prevent the image from being added by adding parameters to the API, so get faster response.

**Comment by mskasal** [comment]
Hello, you can use `excludeUrlPattern ` option.
```javascript
app.use(rendertron.makeMiddleware({
     proxyUrl: args['bot-proxy'],
    injectShadyDom: true,
    excludeUrlPattern: new RegExp('png|jpeg', 'i')
}));
```

**Comment by ifeltsweet** [comment]
@mskasal, this has to happen on the renderer level, not in middleware.

**Comment by AVGP** [comment]
That is under consideration as discussed in #270
