### ISSUE TITLE
Using the window.renderComplete in Angular 6

### ISSUE THREAD

**Issue by FrancisAguilar21** [GoogleChrome/rendertron#226]
Hi,

Sorry for the silly question but I have been researching for hours now on how to implement that call in Angular. I tried inserting it inside one of my components but I don't think it seems to work since it doesn't appear in the list of scripts in the elements tab of my Chrome DevTools.

Here's a picture that shows the script tag isn't being included.

![capture](https://user-images.githubusercontent.com/25190540/46517278-1c9ad880-c8a1-11e8-851f-ac46593a6fd5.PNG)

I inserted the tag this way:

---- sample.component.html ----
`<script type="text/javascript">
	window.renderComplete = hasRendered;
</script>
`

---- sample.component.ts ----
export class SampleComponent {
    ngOnInit() {
        this.route.params.subscribe((params) => {
			this.eventId = params['eventUrl'];
			this.organizerUrl = params['partnerUrl'];
			this.eventService.getEvent(this.eventId).then(event => {
			    this.initializeEventData(event);
			    this.hasRendered = true;
		});
	});
    }
}

**Comment by Romanchuk** [comment]
Why do you insert <script> tag instead of set renderComplete in your code?
```
this.eventService.getEvent(this.eventId).then(event => {
    this.initializeEventData(event);
    window.renderComplete = true
});
```
