### ISSUE TITLE
Missing `Googlebot` keyword in middleware botUserAgents list.

### ISSUE THREAD

**Issue by mskasal** [GoogleChrome/rendertron#229]
These days I am very interested in polymer's [pwa starter kit](https://github.com/Polymer/pwa-starter-kit) which using [prpl-server](https://github.com/Polymer/prpl-server) which using `rendertron`.
So, when I try using Google's `fetch as Google` service for testing SEO, I got blank pages.

<img width="1071" alt="screen shot 2018-10-11 at 14 39 57" src="https://user-images.githubusercontent.com/2426680/46860067-3f386e80-ce18-11e8-81d3-d355c6285d7a.png">

I fixed that with adding `userAgentPattern` option in `prpl-server`'s [cli.ts](https://github.com/Polymer/prpl-server/blob/1e66a56002b294a8121a6089735690b7c45580f4/src/cli.ts#L162) (not configurable from CLI !!, have to fix hard coded)

**I wonder if there is a reason for not including `Googlebot` in this list?**
Thanks.

**Comment by samuelli** [comment]
Hi,

Yes, this is intentional. Please review https://medium.com/dev-channel/polymer-2-and-googlebot-2ad50c5727dd.

Thanks,
Sam
