### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by suhanyujie** [GoogleChrome/rendertron#232]
hello~
When i take a test in `https://render-tron.appspot.com/` for my website `http://laravel.suhanyu.top/`
it's repsponse is:

> Internal Server Error

**Comment by rajikaimal** [comment]
Hi,

I couldn't reproduce this. Did you try 'Take a screenshot' or 'Render and serialize'?

**Comment by suhanyujie** [comment]
Perhaps the netwrok problems few days ago.But now is ok.
Thank you!

**Comment by rajikaimal** [comment]
No problemo 😄
