### ISSUE TITLE
how to set screenshot to folder using express (rendertron-middleware)

### ISSUE THREAD

**Issue by tobiasz18** [GoogleChrome/rendertron#236]
How to make and save in file like 'screenshots' screenshot using rendertron-middleware and whether puppeteer is necessary to do this ?

below is code to serialize & render i want to render and then do screenshots + save this screenshot in folder

const express = require('express');
const rendertron = require('rendertron-middleware');

const app = express();

app.use(rendertron.makeMiddleware({
  proxyUrl: 'http://localhost:3000/render'
}));

app.use(express.static('files'));
app.listen(8080);

**Comment by AVGP** [comment]
What's the use case for doing this on each request?
If the goal is to get screenshots, you can use puppeteer directly, without involving Rendertron.
