### ISSUE TITLE
Handling 301 http status

### ISSUE THREAD

**Issue by Romanchuk** [GoogleChrome/rendertron#237]
Is there any way to handle 301 status (Moved permanently) with LOCATION header?
For instance:
```
<meta name="render:status_code" content="301" />
<meta name="render:header" content="LOCATION: abc.com" />
```

**Comment by mkoczorowski** [comment]
+1

**Comment by AVGP** [comment]
There is no way for this right now. A workaround would be to set a meta refresh:

```
<meta name="render:status_code" content="301" />
<meta http-equiv="refresh" content="0;location=https://abc.com" />
```

If you wish to experiment with support for such a feature, we're welcoming your pull request :)

**Comment by semjuel** [comment]
You can achieve this by adding the next headers:
`
<meta name="render:status_code" content="301" />
<meta name="render:header" content="location:https://google.com" />
`

Don't forget to replace `https://google.com`.
