### ISSUE TITLE
Demo site reported as phishing

### ISSUE THREAD

**Issue by ZeroUnderscoreOu** [GoogleChrome/rendertron#240]
Currently, https://render-tron.appspot.com/ is reported as deceptive site by Google Safe Browsing (and some other services, actually).

Not sure if this is the proper way to report such issue or if anything can be done about it, but I find it a bit ironic.

**Comment by alan345** [comment]
Same here.

![screenshot_20181215-105653](https://user-images.githubusercontent.com/15246526/50046449-436f4b00-0058-11e9-8ac3-d7cbbd9d96c2.jpg)

**Comment by abdonrd** [comment]
Friendly ping to @aomarks and @samuelli!

**Comment by AVGP** [comment]
Filed this as a false-positive... I'll keep you all posted :)

**Comment by abdonrd** [comment]
Thanks Martin!

**Comment by AVGP** [comment]
The issue should be resolved.
