### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by samuelli** [GoogleChrome/rendertron#25]
Add an optional, in-memory rate limiting function.

Rate limit would be x pages rendered per hour. Notably, cache hits are excluded. If the limit is reached, return an appropriate status code & message indicating rate limit has been hit & maybe how long till the rate limit is reset or the next request will be processed.

**Comment by samuelli** [comment]
Closing as not particularly useful & non-trivial to implement. There's a domain whitelist feature if you want to restrict domains.

**Comment by vesper8** [comment]
@samuelli I'm looking for such a domain whitelist feature.. to prevent others from using my Rendertron instance.. but I don't see this mentioned anywhere.. was this removed.. or.. could you please point me to how it works? Thank you!
