### ISSUE TITLE
Iframe is not working

### ISSUE THREAD

**Issue by johnlanz** [GoogleChrome/rendertron#251]
If I enable iframe from Accounts->Iframe all of the users can't login anymore its just blank page.

Also I've got this origin error: "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided" if I use this script from documentation:
`<script>
window.parent.postMessage({
  event: 'login-with-token',
  loginToken: 'your-token'
}, 'http://your.rocket.chat.url');
</script>`

Is there a way we can auto login just using a url instead of postMessage?

**Comment by AVGP** [comment]
Hey @johnlanz , I have a few questions about this:

1. What is "Accounts -> Iframe"? Where does that come from?
2. What is your use case? Rendertron's main use cases aren't exactly for scenarios where users need to log in
3. Do you have a URL where we can see this behaviour?

**Comment by johnlanz** [comment]
sorry wrong issue
