### ISSUE TITLE
How to specify port

### ISSUE THREAD

**Issue by pleerock** [GoogleChrome/rendertron#253]
By default it running on port 3000, how do I change it to my own port since 3000 is already busy?

**Comment by rajikaimal** [comment]
Hi, set `process.env.PORT`

**Comment by gravi2** [comment]
Also checkout my PR #267 for config options.

**Comment by AVGP** [comment]
Here's a sample invocation for running it on port 8080:

```shell
PORT=8080 rendertron
```
