### ISSUE TITLE
500 Internal Server Error with render-tron.appspot.com

### ISSUE THREAD

**Issue by abdonrd** [GoogleChrome/rendertron#261]
If I try the https://render-tron.appspot.com website and click on "Render & serialize" it doesn't work.

Link: https://render-tron.appspot.com/render/https://freestylestats.com

**Comment by abdonrd** [comment]
It seems that the error occurs here:

https://github.com/GoogleChrome/rendertron/blob/6c3f002f489631efb761eedb7c939be9aa7b0a4b/src/renderer.ts#L136-L137

> Error: Evaluation failed: TypeError: Cannot read property 'outerHTML' of undefined

**Comment by abdonrd** [comment]
It seems that the error has appeared when I went from `@webcomponents/webcomponentsjs` `v2.2.1` to `v2.2.2`.

**Comment by abdonrd** [comment]
Changes are only dependencies (`@webcomponents/shadycss` & `@webcomponents/shadydom`):

https://github.com/webcomponents/webcomponentsjs/commits/master

Friendly ping to @azakus.

**Comment by abdonrd** [comment]
@keanulee could you deploy the master branch of `pwa-starter-kit`? So we can check with it:

https://render-tron.appspot.com/render/https://pwa-starter-kit.appspot.com

**Comment by keanulee** [comment]
Was able to reproduce with pwa-starter-kit-hn (https://render-tron.appspot.com/render/https://pwa-starter-kit-hn.appspot.com). Deployed a version that's pinned to webcomponentsjs@2.2.1 and it seems to at least load (https://render-tron.appspot.com/render/https://20190114t092629-dot-pwa-starter-kit-hn.appspot.com).

**Comment by keanulee** [comment]
Pretty sure it's the jump from webcomponentsjs 2.2.1 to 2.2.2, which as @abdonrd mentioned [are version bumps of shadydom and shadycss](https://github.com/webcomponents/webcomponentsjs/commit/86eea48dd4bbe9806689c5ec596462bce0ee23e2), including:

- shadydom 1.3.1 to 1.4.0 [diff](https://github.com/webcomponents/shadydom/compare/v1.3.1...v1.4.0)
- shadycss 1.6.0 to 1.8.0 [diff](https://github.com/webcomponents/shadycss/compare/v1.6.0...v1.8.0)

Notably, the updates [add patching to DOM methods](https://github.com/webcomponents/shadydom/compare/v1.3.1...v1.4.0#diff-e752434456f9e2ba50ab8f76d929ab9d) including `firstElementChild`. Should be the same issue as https://github.com/webcomponents/shadydom/issues/307

**Comment by keanulee** [comment]
Even after locking to 2.2.1 though, the page loads but does not render anything in the `<my-app>` element. We suspect this is related to the bump from `@polymer/lit-element` to `lit-element` and possibly the new static `styles` getter.

**Comment by abdonrd** [comment]
Same here! I have pinned `v2.2.1` and removed the new `static get styles()`.

**Comment by abdonrd** [comment]
Awesome, thanks @keanulee!
I just deployed a new version with `webcomponentsjs@2.2.4` and everything works fine now! 👏
