### ISSUE TITLE
how to specify hostname?

### ISSUE THREAD

**Issue by ukari** [GoogleChrome/rendertron#264]
I noticed [that](https://github.com/GoogleChrome/rendertron/blob/master/src/rendertron.ts#L65) in `Rendertron.initialize()`, it do a `this.app.listen(port, callback)` which will run the service on the default address `0.0.0.0`

**Comment by Wahaj26** [comment]
i would like to create PR @AVGP,  if you say ?

**Comment by AVGP** [comment]
Sure thing!

**Comment by Wahaj26** [comment]
@AVGP PR created.
