### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [GoogleChrome/rendertron#265]
https://travis-ci.org/GoogleChrome/rendertron/builds/485194594

**Comment by AVGP** [comment]
It's flaky and I'm not sure why. Here is the same commit passing: https://travis-ci.org/GoogleChrome/rendertron/builds/486198825?utm_medium=notification&utm_source=email

**Comment by DanielRuf** [comment]
Shall we retrigger CI?

**Comment by AVGP** [comment]
Well the latest build is green :) I think I'll spend some time next week trying to find out what's the shaky bit at play here...
