### ISSUE TITLE
selector support

### ISSUE THREAD

**Issue by jooohn** [GoogleChrome/rendertron#269]
Does anyone like the idea of taking a screenshot of a specific DOM element? I want this feature to detect changes of webpages, so I personally tried it: https://github.com/jooohn/rendertron/commit/bcd2a62efa27e242801881f19c870b3b7b0aeb53

You can try this online:
https://rendertron-selector.herokuapp.com/

```
curl -X POST -H 'Content-type:application/json' https://rendertron-selector.herokuapp.com/screenshot/https://example.com -d '{"selector":"h1"}'
```

the result:
![example](https://user-images.githubusercontent.com/2661835/52795571-66989400-30b5-11e9-9ca4-31cc7b294989.jpg)

I'd like to here your opinion :)

**Comment by AVGP** [comment]
That is a really neat feature, I'd love to see a PR for this :shipit:
