### ISSUE TITLE
Abort on non-essential requests (stylesheets, images)

### ISSUE THREAD

**Issue by mavame** [GoogleChrome/rendertron#270]
Per this article, it may be a good idea to add this to the core renderer library:
https://developers.google.com/web/tools/puppeteer/articles/ssr#abort

I see another open issue (#225) where the suggested solution is to use `excludeUrlPattern` but that assumes you're using the express middleware with Rendertron.

I can't imagine a use case where you'd be using this library for SEO, and you'd want rendertron to also request images and stylesheets. This could speed up render times for everyone.

**Comment by mavame** [comment]
I'm happy to contribute a PR for this if anyone else thinks its a needed feature.

**Comment by reedzhao** [comment]
> I'm happy to contribute a PR for this if anyone else thinks its a needed feature.

I like to have this.  We use nginx to proxy all googlebot requests to rendertron.  There is no nodejs middleware in our stack.

**Comment by mavame** [comment]
@reedzhao feel free to use my fork which includes this change. I will PR into the main rendertron repo if/when a maintainer tells me they agree with the proposal.

https://github.com/mavame/rendertron

**Comment by reedzhao** [comment]
> @reedzhao feel free to use my fork which includes this change. I will PR into the main rendertron repo if/when a maintainer tells me they agree with the proposal.
> 
> https://github.com/mavame/rendertron

Exactly what we need. Thanks!

**Comment by ifeltsweet** [comment]
@samuelli, can we please have this?

**Comment by AVGP** [comment]
I'm not seeing the actual change (besides one commit that updates the README) in your fork, but I'm intrigued. I think it should be a parameter per request or in the config to let people choose when/if they want that, but the feature itself makes sense to me.

**Comment by vesper8** [comment]
@mavame @AVGP is right, your fork doesn't include any actual changes besides changes in the Readme.md.. did you forget to commit the actual change that prevents the pulling of images and stylesheets? I think this would be a good-to-have as well for everyone

**Comment by lwyj123** [comment]
any updates? I am reading https://developers.google.com/web/tools/puppeteer/articles/ssr#optimizations but not found a solution in rendertron

**Comment by AVGP** [comment]
Well, if someone wants to implement this, we can move this forward =)

**Comment by AVGP** [comment]
If someone revisits this and posts a PR, we'll look into it :)

**Comment by iranagame** [comment]
@AVGP Any chance to have this on the upcoming update? it's really slow on pages with many images...
