### ISSUE TITLE
Chrome Framework exceeds maximum allowed filesize for Google AppEngine

### ISSUE THREAD

**Issue by coolbung** [GoogleChrome/rendertron#276]
I am trying to deploy to Google AppEngine. I have checked out the code and verified that I am able to run rendertron locally.  However when I try to deploy to GAE using the command 

```bash
gcloud app deploy app.yaml --project rendertron-test-233009
``` 
the deployment fails with the error

`
ERROR: (gcloud.app.deploy) Cannot upload file [/Users/ashwindate/Documents/git/rendertron/node_modules/puppeteer/.local-chromium/mac-588429/chrome-mac/Chromium.app/Contents/Versions/71.0.3542.0/Chromium Framework.framework/Versions/Current/Chromium Framework], which has size [137191564] (greater than maximum allowed size of [33554432]). Please delete the file or add to the skip_files entry in your application .yaml file and try again.
`

**Comment by AVGP** [comment]
Weird, I can't reproduce that here - could you try again with the current version of Chromium?
