### ISSUE TITLE
Add an option to disable removal of script tags

### ISSUE THREAD

**Issue by frontendr** [GoogleChrome/rendertron#277]
I am assuming some very smart people found more than enough reason to fully remove script tags after the render has completed in the `stripPage` function. I'm trying to use rendertron to pre-render a react application. The result is then used as response in a Django application.

It works like a charm except for the fact that the React app can never work again in the pre-rendered code because all my script tags are gone! That's why I would like to ask to put this under a config.

I see an opportunity to add this to #267 (PR: Enhance Rendertron config) but I don't know if that's the way to go. Perhaps @gravi2 could add this feature to the PR?

**Comment by adi9999** [comment]
Yes app not work after render because all script gone now and also global variables , Anyone knows how to solve this issue?

**Comment by frontendr** [comment]
@adi9999 See the commits on my fork which works fine:
https://github.com/frontendr/rendertron/commits/feature/configure-strip-page

https://github.com/frontendr/rendertron/commit/f7c95baf735cfc36096a5c70a3385fea5c7e6d5b adds the config variable in which you can specify the selector of the elements to remove.
https://github.com/frontendr/rendertron/commit/2e885e5d28e5febb3383df70c7ce7924135a57ff Fixes the global variable issue in the removal function by injecting a global variable named `window.__rendertronConfig`.

I would love some input on how to make this change ready for a pull request.

**Comment by AVGP** [comment]
Thanks for your ideas and the work you've done in your fork, @frontendr!

The main use case for Rendertron is [dynamic rendering](https://developers.google.com/search/docs/guides/dynamic-rendering), i.e. rendering a client-side rendered web app into **static HTML**. 

The use case you describe sounds like you want [re-hydration](https://developers.google.com/web/updates/2019/02/rendering-on-the-web#rehydration). For React, that can be achieved with [react-snap](https://github.com/stereobooster/react-snap) or by using [Next.js](https://nextjs.org/) as a higher-level framework.
