### ISSUE TITLE
Only Rendering the index page.

### ISSUE THREAD

**Issue by AndroidLibrariesYoutube** [GoogleChrome/rendertron#278]
I have added middleware in my express server and I am running an angular app with the express server. Rendertron only rendering my index.html page with all the javascript. But it's not rendering the other components. Can anyone tell what's the problem?

**Comment by frontendr** [comment]
Do you mean the Angular application is not rendered and you only see the basic output of your `index.html`? If it does render the Angular application, are you actually requesting the subpages?
Do you see any logging in the running Rendertron service when you are requesting the subpages?

**Comment by AndroidLibrariesYoutube** [comment]
I don't see any logging in the Rendertron service. My angular application is running properly but rendertron is not going on the subpages It only showing the home page with working api's. How I can register subpages can you help me?

**Comment by frontendr** [comment]
Rendertron works by request. You request a page for Rendertron to render.
It does not crawl your site automatically.

So if you want to render subpages you'll have to manually request each
page. For example, if your Rendertron runs on `http://localhost:3000`, you
i'll request these pages:

- `http://localhost:3000/render/http://mysite.com/` and store the result
- `http://localhost:3000/render/http://mysite.com/subpage1` and store the
result
- `http://localhost:3000/render/http://mysite.com/subpage2` and store the
result

Then your results will contain the rendered pages.

**Comment by AndroidLibrariesYoutube** [comment]
Ok but I am bit confused. I need to save those pages in any database or I can do at runtime. And how I can pass the subpages URL I don't see any documentation about that. Thanks for helping.

**Comment by frontendr** [comment]
The implementation depends on your own system. Rendertron does 1 thing: render a page and return the resulting HTML. What you do with the resulting HTML is up to you.

When you start the Rendertron service you'll see it's listening on `localhost:3000` or something.

You'll have to request a render of your page by yourself. The API is described in the [README](https://github.com/GoogleChrome/rendertron#api). Basicly it's making a HTTP request to `http://localhost:3000/render/<url encoded url of your page>`. The response is the rendered HTML.

So you request a render of a specific URL, you get the HTML. That's it, that's what Rendertron does. It's like a browser (it actually is) but the HTML it returns includes elements created by JavaScript.

Now for implementations several so called middlewares have been developed. I'm currently developing one myself for [Python Django applications](https://github.com/frontendr/python-rendertron). Which middleware you use depends on the system you are using. See the list of middleware also in [the README](https://github.com/GoogleChrome/rendertron#middleware).

**Comment by AndroidLibrariesYoutube** [comment]
Ok, I will try it. Thanks.

**Comment by AndroidLibrariesYoutube** [comment]
I tried to debug but I didn't find any. The problem is the same it only rendering the same index.html page. It's not rendering other components of my site. I am testing with a user-agent extension in chrome

**Comment by AVGP** [comment]
As @frontendr said, Rendertron takes a URL and renders that exact URL into static HTML.
It can be used behind a reverse-proxy or as part of any server-side setup, like an express.js server.
You can check out [this codelab](https://codelabs.developers.google.com/codelabs/dynamic-rendering/index.html?index=..%2F..index#0).

For Angular, you could also try [Angular Universal](https://angular.io/guide/universal) as an alternative to Rendertron.
