### ISSUE TITLE
Argument of type '"unhandledRejection"' is not assignable to parameter of type 'Signals'.

### ISSUE THREAD

**Issue by fxalvarezd** [GoogleChrome/rendertron#281]
I cloned the repo from scratch following the steps below:
```
git clone https://github.com/GoogleChrome/rendertron.git
cd rendertron
npm install
npm run build
```

and during the `build` process I'm getting this typing error.

`Argument of type '"unhandledRejection"' is not assignable to parameter of type 'Signals'.`

**Comment by fxalvarezd** [comment]
tried the exact same process again after a while and it worked... not sure if it was a hiccup with a dependency...

**Comment by gravi2** [comment]
@fxalvarezd I was facing the same issue. I think its still a issue. Try this, get the latest code, delete the package-lock.json and try same steps. You should see the issue again. Looks like some of the latest packages bring in a node package that does not like process.on('unhandledRejection', logUncaughtError);  

https://github.com/GoogleChrome/rendertron/blob/master/src/rendertron.ts#L151

I am recomment reopening the issue for @AVGP to comment/confirm the issue and if the package-lock.json was deliberately locked for specific versions of some packages.

**Comment by ilicmarko** [comment]
I can also confirm this. As @gravi2 I am using Ubuntu.

```
Node: v11.9.0
NPM: 6.5.0
Yarn: 1.13.0
```
I tried `yarn` and `npm` same issue.

**Comment by hjpunzalan** [comment]
bump this is still happening
