### ISSUE TITLE
AdSense

### ISSUE THREAD

**Issue by philkunz** [GoogleChrome/rendertron#283]
Does rendertron in any way affect AdSense crawling compatibility?

Just asking since no clicks and views are registered through AdSense on an otherwise working page written with lit-element (with Ads showing as normal of course).

**Comment by AVGP** [comment]
Possibly as it removes JavaScript from the rendered page. What is your use case for using Rendertron, if I may ask?

**Comment by AVGP** [comment]
Feel free to reopen this issue with more information how to reproduce the problem.
