### ISSUE TITLE
works on rendertron but not on google test

### ISSUE THREAD

**Issue by ohabash** [GoogleChrome/rendertron#284]
Im going to google and simulating a google crawl and the page source does not show the pages content. 

If i go to `view-source:https://render-tron.appspot.com/render/https://fornida-boilerplate.herokuapp.com` the page source shows all content. 

1. what is a better way to test locally?
2. why does `view-source:https://render-tron.appspot.com/render/https://fornida-boilerplate.herokuapp.com` work but not on **google search console**?

```
// api routes
app.use("/api", require("./api/api"));
app.use('/sms', require('./api/sms'));

// redertron middleware
app.use(rendertron.makeMiddleware({ proxyUrl: `${renderUrl}` }));

// serve angular app
app.use(express.static(path.join(__dirname, '/dist/browser/')));
app.get('/*', (req, res) => res.sendFile(path.join(__dirname, '/dist/browser/')));
```

**Comment by philkunz** [comment]
I think you are confused by either of the following things:

* rendertron (puppeteer) is a different chrome version than Google Search (pretty old with v41)
* The Googlebot Useragent is not included in the default rendertron middleware's user agent list. You have to modify that yourself like so: https://gitlab.com/pushrocks/smartexpress/blob/master/ts/smartexpress.tools.rendertron.ts

**Comment by tkrugg** [comment]
Is there a reason for not including googlebot in the default user agents list?

**Comment by philkunz** [comment]
yes! Things have changed since then. GoogleBot now is shortly behind the official chrome and currently at chrome version 74+ No need to send GoogleBot through rendertron whatsoever.
