### ISSUE TITLE
Rendertron appspot marked as phishing

### ISSUE THREAD

**Issue by InnovativeInventor** [GoogleChrome/rendertron#286]
https://www.virustotal.com/#/url/add34b8bddc3d26585223851e00d43572103d94096a924c1d10e1b7a50a17b46/detection. 

Regression of #240?

**Comment by AVGP** [comment]
Does anyone know how to report this to BitDefender and Sophos?

**Comment by citricacid-pl** [comment]
Avast is detecting this as phishing too.

<img width="1440" alt="Zrzut ekranu 2020-02-19 o 16 59 29" src="https://user-images.githubusercontent.com/745572/74851253-455b2b00-533b-11ea-94f5-424abae31256.png">

**Comment by AVGP** [comment]
For Avast I could report it as false positive, at least.
