### ISSUE TITLE
Rendertron not working for Facebook

### ISSUE THREAD

**Issue by ohabash** [GoogleChrome/rendertron#287]
Im using `rendertron-middleware` and it is not working for facebook bots. Any tips?
```
// redertron middleware
const bots = ['googlebot', 'Baiduspider', 'bingbot', 'duckduckbot', 'slurp', 'Facebot', 'Embedly', 'facebookexternalhit', 'LinkedInBot', 'outbrain', 'yandexbot', 'pinterest', 'quora link preview', 'rogerbot', 'showyoubot', 'Slackbot', 'TelegramBot', 'Twitterbot', 'vkShare', 'W3C_Validator', 'WhatsApp', ]
app.use(rendertron.makeMiddleware({
  proxyUrl: `${renderUrl}`,
  userAgentPattern: new RegExp(bots.join('|'), 'i')
}));
```

**Comment by AVGP** [comment]
I can't reproduce that with your exact bot list. I have a page that uses JS to generate the OpenGraph meta tags and it shows up fine in the share debugger when rendered via Rendertron:

<img width="723" alt="Sharing_Debugger_-_Facebook_for_Developers" src="https://user-images.githubusercontent.com/370246/64544453-63733700-d36a-11e9-9249-969cce9c3316.png">

Could you:

1. Check if you get the rendered version when doing a request via `curl -H "User-agent: facebot" http://your-server-or-localhost:1234/whatever-url-you-need` and see if that contains the `x-renderer` header as well as the rendered meta tags
2. Try to reproduce it on glitch.com so I can test it, too?

**Comment by AVGP** [comment]
Feel free to reopen this issue with more information how to reproduce the problem.
