### ISSUE TITLE
HttpConnectionTimeout for Twitter Card

### ISSUE THREAD

**Issue by nicowagner** [GoogleChrome/rendertron#288]
Hi!
Im receiving this error when triyng to render my card on twitter validator, the app is working fine with facebook card, but not twitter.

Twitter error:
ERROR: Failed to fetch page due to: HttpConnectionTimeout

Someone could solve this?

Thanks!

**Comment by rmatsuura** [comment]
I also suffer from the same problem.

**Comment by abdonrd** [comment]
Same here!

**Comment by kokaprathyush** [comment]
Same problem

**Comment by AVGP** [comment]
Could you share a sample URL to test?

**Comment by AVGP** [comment]
Seems to work for the demo instance, at least with a very simple test page:

<img width="992" alt="Card_Validator___Twitter_Developers" src="https://user-images.githubusercontent.com/370246/64538765-8b5d9d00-d360-11e9-8ff9-f75644579d52.png">

**Comment by AVGP** [comment]
Feel free to reopen this issue with more information.
