### ISSUE TITLE
Explicit render flag

### ISSUE THREAD

**Issue by Supamiu** [GoogleChrome/rendertron#289]
As I'm working with some firebase stuff and some requests that can pretty much hang for dozens of seconds even if they are useless for the rendering process, I wanted to use a render flag to tell the renderer I finished rendering my page.

So I found this PR: #126 that adds exactly what I want.

I implemented it inside my page and realized that it wasn't working.

By looking at the source code, it seems like this has been entirely removed and there's no way to tell the renderer when you finished the rendering explicitly.

Is this planned for a future release? Or should I just try to implement it and PR?

Edit:

By taking a look at pupeteer, it seems like the best I can do for now is to change "networkidle0" for "networkidle2", but it's sadly not enough to fix my issue :/

**Comment by AVGP** [comment]
This seems to have been removed with the switch to Puppeteer indeed.
Unfortunately, [it seems that Puppeteer isn't going to add the possibility to listen to events](https://github.com/GoogleChrome/puppeteer/issues/2455)..

Closing this issue for now, feel free to reopen, if you wanna take a stab at this with a PR
