### ISSUE TITLE
Issue on Product version of Styled-Components when render with Rendertron

### ISSUE THREAD

**Issue by AJ-7885** [GoogleChrome/rendertron#291]
have very simple sample app which build Create React App + Styled-Components to prove this issue. But I have real big application which I am facing this issue which I am going to explain it below.

I would like to pre-render this app with Rendertron for SEO/GoogleBots and etc. But the problem is when I build PRODUCTION version of React App which use Styled-Components . all the style will be missing on static version which Rendertron produced, but from other side if I try the same workflow with dev-server of app , everything looks fine .

So far I know there is different on PROD version and DEV version of my application when I render it with Rendertron . But I am not sure what cause this issue and how I can fix this issue .

I am looking for solution or idea which can help me to solve this issue .

Here is my sample code which I peppered for test .

https://github.com/AJ-7885/test-styled-component-with-rendertron

Here is screen shot from different version of Rendered version by Rendertron base on PROD or DEV version of the same application .

![Screenshot 2019-05-31 at 13 30 12](https://user-images.githubusercontent.com/42003122/58704633-02bc8180-83ad-11e9-97c8-dd6d8858d83b.png)

![Screenshot 2019-05-31 at 13 28 05](https://user-images.githubusercontent.com/42003122/58704644-08b26280-83ad-11e9-9457-3f6cbddc356d.png)

https://stackoverflow.com/questions/56394337/issue-on-product-version-of-styled-components-when-render-with-rendertron

**Comment by AVGP** [comment]
First things first: Thank you for the fantastic bug report. The test case was super helpful!

It seems that you found the answer, according to StackOverflow. The option to directly inject into CSSOM makes serialising from the DOM impossible, hence the issue you were seeing.
