### ISSUE TITLE
Rendertron on Ubuntu works find for some hours but abruptly stops and needs to be started manually

### ISSUE THREAD

**Issue by Badhumvee** [GoogleChrome/rendertron#293]
Hi I have installed Rendertron on a Ubuntu server.  It works just fine as expected (and we have a very simple page prerender use case).  But after few hours (random, ranges from 2 hrs to 1 day) we start getting 'connection refused' on or calls on port 3000 from the server, and when we check the server, rendertron is not listening on the port 3000 anymore.   
Any idea why the rendertron is stopping abruptly?  Any help would be greatly appreciated.

**Comment by AVGP** [comment]
The process continues running but it stops listening to port 3000?

**Comment by AVGP** [comment]
I can't reproduce this.

If you have a way to reproduce this behaviour, please feel free to reopen this bug and add information.
