### ISSUE TITLE
Enabling and/or increasing Cashe use of Rendertron on its own server

### ISSUE THREAD

**Issue by Badhumvee** [GoogleChrome/rendertron#294]
HI, I am running Rendertron on its own server to prerender my SPA pages.  Often it takes too long for rendertron to respond with the prerendered page.  So a few questions arise regarding its use of Cache:
1) Does installing Rendertron configure its own Caching?
2) Is there anything we can do to allow either Rendertron or the headless Chrome to Cache using more local memory ?
3) Does the headless version of google chrome Cache static assets as specified by the server metadata?

**Comment by AVGP** [comment]
1. Caching is optional and off by default. 
2. Once #227 lands, you have the option to use an in-memory cache.
3. Not sure, that needs some investigating...

**Comment by azardev** [comment]
on my server cashing is only working for mobile mode, any same issue?
