### ISSUE TITLE
Sending the SPA-response html to Rendertron instead of URL of page

### ISSUE THREAD

**Issue by Badhumvee** [GoogleChrome/rendertron#295]
Sending the SPA-response html to Rendertron instead of URL of page

I would like to send the response from our Single Page Application forwarded to the rendertron (not the url) to be prerendered and then send that prerendered html back.  
This way, I am saving on a couple of hops which adds significant delays on our end to get a response from rendertron.  

So can we have something like: 

www.rendertronIPaddress/RenderThisHTML/string="<html><head>.... <body>...</html>"

Thanks a lot.

**Comment by AVGP** [comment]
Unless that has all assets inlined (CSS, JS, images), it would still need to make a network request to whatever serves the SPA. I'm not sure the potential gain would justify the additional complexity of such feature. That being said, you can of course explore that option by modifying Rendertron yourself.
