### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by whitecolor** [GoogleChrome/rendertron#296]
There is really a lack of explanation of how caching works and what are recommendations for implementing it if not embedded works.

**Comment by AVGP** [comment]
Right now it uses the Google Cloud datastore and items will expire after 24 hours ([see here](https://github.com/GoogleChrome/rendertron/blob/master/src/datastore-cache.ts#L54)) which is a hard-coded value.

We're in the process of also providing a way to use an in-memory cache and additional documentation.

**Comment by vesper8** [comment]
@AVGP I would really like more control over the cache... does the in-memory support redis? if not what does it use?

Is there a cache/recache API that lets you know if an url is cached, let's you invalidate it / queue a recache

Would really like more options too, such as using AWS S3 for storing cache, or using the filesystem, for machines that are low on memory. For cases where the user does not wish to use Google Cloud.

Thank you!

**Comment by maxisam** [comment]
support redis would be nice.
