### ISSUE TITLE
new package version

### ISSUE THREAD

**Issue by gko** [GoogleChrome/rendertron#297]
Can you publish new package version? Cause there was no version since this was added:
[src/renderer.ts#L27](https://github.com/GoogleChrome/rendertron/blob/4f396d4d522cd39ceaa0b33b203afd81371e28f5/src/renderer.ts#L27)

Thank you

**Comment by AVGP** [comment]
We'll publish a new version of Rendertron and rendertron-middleware soon. It's going to be a major version change for rendertron-middleware, probably.

**Comment by vesper8** [comment]
@AVGP any update on when a new version will be published? I believe there has been a ton of commits since the last release

**Comment by AVGP** [comment]
The plan is to finalize all the PR merges and docs and release the next major version within this month.

**Comment by AVGP** [comment]
3.0.0 just landed 🎉
