### ISSUE TITLE
Vulnerability report

### ISSUE THREAD

**Issue by tayambamwanza** [GoogleChrome/rendertron#298]
I was happily installing rendertron and then I saw this (How worried should I be?):

![Screenshot from 2019-07-15 11-42-13](https://user-images.githubusercontent.com/11971384/61207638-e757cc80-a6f5-11e9-9fde-e7074c88f5c7.png)

**Comment by AVGP** [comment]
Many of those are in the `devDependencies`, but still: Good point.
Once #306 lands, this will be resolved :)
