### ISSUE TITLE
Renderton + nginx + error_log

### ISSUE THREAD

**Issue by nd093** [GoogleChrome/rendertron#300]
Hello,
Thank you in advance for for your help!

I have implemented renderton with nginx server.
What I need is to log errors only generated from rendertron server.
Any suggestion ?
Please let me know if more information needed.
Thank you

**Comment by AVGP** [comment]
Hey @nd093 - how are you running Rendertron? It logs errors to its STDERR.

You can redirect the error logging to a file. For example:

```
cd rendertron
mkdir -p /var/log/rendertron
npm run 1> /var/log/rendertron/info.log 2> /var/log/rendertron/error.log
```

This will write info messages (e.g. the requests made to your Rendertron instance) to `/var/log/rendertron/info.log` and errors to `/var/log/rendertron/error.log`
