### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by amannguptaggg** [GoogleChrome/rendertron#303]
'tsc' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rendertron@2.0.1 build: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rendertron@2.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2019-08-29T09_28_57_547Z-debug.log
PS C:\Users\DELL\ion\portfolio\portfolio\rendertron>

**Can Anyone solve my issue? Please**

**Comment by AVGP** [comment]
Did you run `npm install` before? That should have installed the typescript compiler (`tsc`).

**Comment by amannguptaggg** [comment]
yup...problem is solved.
thanks for replying. :)

**Comment by AVGP** [comment]
Perfect, thank you!
