### ISSUE TITLE
[Docs] Write documentation on deployment via gcloud

### ISSUE THREAD

**Issue by AVGP** [GoogleChrome/rendertron#317]
- Create a new file `docs/deploy.md`
- Write a section on how to deploy Rendertron to Google Cloud Platform

To write this, see [the deployment section of the codelab](https://codelabs.developers.google.com/codelabs/dynamic-rendering/index.html?index=..%2F..index#3).

**Comment by Wahaj26** [comment]
@AVGP please let me know if this documentation is enough or need some more explanation.(https://github.com/GoogleChrome/rendertron/pull/332)
