### ISSUE TITLE
[Docs] Document deploying Rendertron via Docker

### ISSUE THREAD

**Issue by AVGP** [GoogleChrome/rendertron#319]
- Create or edit `docs/deploy.md`
- Add a section that explains how to deploy Rendertron via Docker

The puppeteer docs [have some pointers](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker) and there was a [pull request with a Dockerfile](https://github.com/GoogleChrome/rendertron/pull/220)

**Comment by hugo-ma-alves** [comment]
Hello @AVGP 
I created a PR with a basic example of how to run rendertron in a docker container. https://github.com/GoogleChrome/rendertron/pull/480

Hope it is useful.
