### ISSUE TITLE
Rendertron - inconsistent html rendering

### ISSUE THREAD

**Issue by grachit** [GoogleChrome/rendertron#320]
@abdonrd 
At times, I am observing that html rendered by rendertron is not consistent and misses some html elements from pages. 
For e.g. Rendering of Carousel section is not always consistent. Number of elements rendered within it differs.

Are there any setting changes we need to do? It would be great if we can get some help over it.

**Comment by AVGP** [comment]
Do you have a reduced test case for us to check?

**Comment by grachit** [comment]
@AVGP  I working on details.

**Comment by AVGP** [comment]
@grachit Any updates?

**Comment by grachit** [comment]
Can u try tests on following page? Contents rendered are not always consistent. 

[https://www.walmart.com/ip/ZOSI-Outdoor-1080P-HD-WiFi-Wireless-IP-Security-Bullet-Camera/982404880](url)

**Comment by grachit** [comment]
@AVGP any update on it?

**Comment by grachit** [comment]
@AVGP Kindly update us on it.

**Comment by AVGP** [comment]
Thanks for the patience - when I tested this, what I did see is that sometimes the page takes longer than the default timeout period (10 seconds), which can lead to incomplete renders.

You can configure this by specifying a different timeout in your `config.json`.
