### ISSUE TITLE
Add an API endpoint to invalidate a cached URL

### ISSUE THREAD

**Issue by AVGP** [GoogleChrome/rendertron#342]
The API endpoint should let users specify a URL they want to remove from cache and then remove it.
The two existing cache providers [datastore-cache](https://github.com/GoogleChrome/rendertron/blob/master/src/datastore-cache.ts) 
and [memory-cache](https://github.com/GoogleChrome/rendertron/blob/master/src/memory-cache.ts) already contain code to delete a 
single entry from their cache, but don't expose this as a method yet.

Authentication for this is out of scope for this issue as that is responsibility of the operator 
of the Rendertron server and not part of Rendertron.

Goals of this issue:

- Add a new API endpoint in [`src/rendertron.ts`](https://github.com/GoogleChrome/rendertron/blob/master/src/rendertron.ts) - for example `/invalidate`
- Add a `removeEntry` method in [`src/datastore-cache.ts`](https://github.com/GoogleChrome/rendertron/blob/master/src/datastore-cache.ts) and [`src/memory-cache.ts`](https://github.com/GoogleChrome/rendertron/blob/master/src/memory-cache.ts) to delete a single key by URL
- Add tests for the API endpoint and the cache providers
- Add docs for the new API endpoint

**Comment by krishnan-r** [comment]
Hi, 
I found this issue from the Hacktoberfest label. I'd like to work on it. I'll raise a PR shortly.

**Comment by AVGP** [comment]
@krishnan-r I assigned the issue to you.

Feel free to ask questions and open the PR as work-in-progress :) We're happy to help!

**Comment by vesper8** [comment]
here is my makeshift standalone cache/check/invalidate/recache solution using Laravel.. in case it might serve as inspiration

example usage: `php artisan rendertron recache https://www.example.com/uri`

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class Rendertron extends Command
{
    protected $signature = 'rendertron {action} {url}';

    protected $description = 'Recache a URL via Rendertron';

    protected $datastore;

    public function handle()
    {
        $keyFile = json_decode(file_get_contents(base_path('path/to/rendertron-service-account-credentials.json')), true);

        $this->datastore = new \Google\Cloud\Datastore\DatastoreClient([
            'keyFile' => $keyFile,
        ]);

        $url = $this->argument('url');
        $key = $this->datastore->key('Page', "/render/{$url}");

        switch ($this->argument('action')) {
            case 'check':
                if ($this->datastore->lookup($key)) {
                    $this->info("{$url} - is cached");
                } else {
                    $this->info("{$url} - is not cached");
                }
            break;

            case 'cache':
                if (!$this->datastore->lookup($key)) {
                    $this->info("{$url} - caching");

                    $this->cache($url);
    
                    if ($this->datastore->lookup($key)) {
                        $this->info("{$url} - has been cached successfully");
                    }                        
                } else {
                    $this->info("{$url} - is already cached");
                }
            break;            

            case 'invalidate':
                if ($this->datastore->lookup($key)) {
                    $this->info("{$url} - invalidating");

                    $this->datastore->delete($key);

                    if (!$this->datastore->lookup($key)) {
                        $this->info("{$url} - has been invalidated successfully");
                    }
                } else {
                    $this->info('nothing to invalidate');
                }
            break;

            case 'recache':
                if ($this->datastore->lookup($key)) {
                    $this->info("{$url} - invalidating");
                    $this->datastore->delete($key);
                }

                $this->info("{$url} - caching");

                $this->cache($url);

                if ($this->datastore->lookup($key)) {
                    $this->info("{$url} - has been cached successfully");
                }
            break;
        }
    }

    protected function cache($url)
    {
        $curl = curl_init($url);

        curl_setopt($curl, CURLOPT_USERAGENT, 'Googlebot');
        curl_setopt($curl, CURLOPT_FAILONERROR, true);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

        curl_exec($curl);
        curl_close($curl);
    }
}
```

**Comment by krishnan-r** [comment]
Hi @AVGP,  I have opened a work in progress PR. Will discuss on refining it shortly. Thanks for the help :)

@vesper8 Thanks for the snippet, I will look into that and the cloud datastore cache part.
