### ISSUE TITLE
How can I speed up rendering?

### ISSUE THREAD

**Issue by gigamesh** [GoogleChrome/rendertron#348]
The team I've been working with has been struggling to get rendertron to work consistently for a long time. I think the main problem is that it takes too long (often 10-15 seconds), so social media bots timeout. I've tried adding `"cache": "datastore"` to the config.json and upped the timeout, but it didn't help much. The meta tag data only shows up in social media cards about half the time, at best. And considering the cost of App Engine, we'd really like to get this working reliably.

I've looked at past threads but they didn't help much.  Any ideas?

**Comment by vesper8** [comment]
are you sure your cache is working? when I visit a page that's been cached (in the datastore) it loads the html instantly.. it in fact loads the page much faster this way then by visiting the site normally

Are you sure that the social media user agent is caught by your middleware and being routed to the cache?

Maybe you need to increase the cache expiry, by default it's set to just 1 day but I set it to 1 month

**Comment by gigamesh** [comment]
Thanks for the reply 

I think the cache is working yes (loads instantly after the 2nd try), and I've verified that the user agent is caught & rerouted. 

How do I increase the cache expiry?

**Comment by vesper8** [comment]
As far as I know there isn't yet a convenient way to change the cache expiry, but I easily got it working by simply editing this line in my local rendertron installation: https://github.com/GoogleChrome/rendertron/blob/c0d47e15700b3e6fc1cf35f009f5a545e45361f6/src/datastore-cache.ts#L54

Then just restart the node worker (I use PM2 for this) and voila. You can confirm that it's working by inspecting your entries inside the Google Datastore

**Comment by AVGP** [comment]
Closing this issue. If you have further input or want to implement a config option for this, let us know.
