### ISSUE TITLE
rendertron and images lazy load

### ISSUE THREAD

**Issue by bill-pux** [GoogleChrome/rendertron#349]
Hi there,

first off all, thanks for the good work, keep it up !

then i have a newbie question related to the https://render-tron.appspot.com/
page. 
How does it work ? 
Whenever i try to render or screenshot my site (www.rsi.ch) 
it reloads without giving me any feedback ... just reloads and that's it.
Is there any geo limitation in the use ?
What can i do to see the result of a "proper" install of rendertron ?

greetings, and thanks again.
cp

**Comment by AVGP** [comment]
Not sure what's causing the issue, but the screenshot works fine for me.

What browser are you using? Have you tried it from multiple devices?

There's no limitations, besides a 10s timeout.

https://render-tron.appspot.com/screenshot/https://rsi.ch/?width=1366&height=670 returns a screenshot as expected when I try it.

**Comment by bill-pux** [comment]
Then it might be all the security checks we're here in the office.

thanks so much.
