### ISSUE TITLE
Timeout is hardcoded for screenshot instead of using the value from config

### ISSUE THREAD

**Issue by ramyhhh** [GoogleChrome/rendertron#351]
I noticed that no matter what you put in config for timeout, it's not affecting for screenshot. So I found that in the file [renderer.ts](https://github.com/GoogleChrome/rendertron/blob/master/src/renderer.ts#L192) line 192 it's hard coded as 10 seconds instead of reading it from ```this.config.timeout```

**Comment by AVGP** [comment]
Hey @ramyhhh - would you be interested in making the fix yourself and opening a pull request?

**Comment by ramyhhh** [comment]
Sure!

**Comment by AVGP** [comment]
Awesome, let me know if you need anything to make it happen :)

**Comment by vladimirdjurdjevic** [comment]
The same goes for the port. Port is set to: `process.env.PORT || 3000`, and value from config is ignored. Also, I don't see how memory cache works. It seems like only `datastoreCache` boolean is used from the config.

**Comment by ramyhhh** [comment]
@vladimirdjurdjevic I've checked ```src/rendertron.ts``` and found out that **port** is getting filled from process or config [init port](https://github.com/GoogleChrome/rendertron/blob/master/src/rendertron.ts#L22). Also **cache** is controlling which store to load in this [line](https://github.com/GoogleChrome/rendertron/blob/master/src/rendertron.ts#L49)

**Comment by ramyhhh** [comment]
@AVGP I did the **pr** a while ago, I'm not sure if you guys saw it! I came across it today and found out that it's still open [Pull Request](https://github.com/GoogleChrome/rendertron/pull/352)

**Comment by AVGP** [comment]
Merged!
