### ISSUE TITLE
Rendertron Middleware - Add optional callback for hostname

### ISSUE THREAD

**Issue by brettwillis** [GoogleChrome/rendertron#354]
Consider when the `rendertron-middleware` is deployed for example on Cloud Run behind a Firebase Hosting site, where requests are directed via Firebase Hosting which has a different domain/hostname from the Cloud Run instance.

The middleware uses [`req.get('host')`](https://github.com/GoogleChrome/rendertron/blob/c0d47e15700b3e6fc1cf35f009f5a545e45361f6/middleware/src/middleware.ts#L116) which would resolve to the URL of the Cloud Run instance.

If static resources are served via Firebase Hosting, and requests are sent to the Cloud Run instance because of above, then the page will fail to load and render.

What is needed in this scenario is a callback that allows us to override the hostname sent to the proxy; which in this case using the Firebase Hosting hostname rather than the Cloud Run hostname.

For example:

    app.use(rendertron.makeMiddleware({
      proxyUrl: 'http://my-rendertron-instance/render',
      hostnameCallback: (req) => {
        // Requests via Firebase Hosting have headers like:
        //   via: '1.1 Firebase Hosting'
        //   x-forwarded-host: <my-custom-domain>
        if (/Firebase Hosting/.test(req.get('via')) && req.get('x-forwarded-host') === 'my-custom-domain') {
          return 'my-custom-domain';
        } else {
          return req.get('host');
        }
      }
    }));

Perhaps the documentation should also include a security warning about determining the hostname from untrusted user input such as request headers. Note how the example only allows the known hostname.

**Comment by AVGP** [comment]
would you be interested in implementing this?
