### ISSUE TITLE
internal error at the moment on appspot.com

### ISSUE THREAD

**Issue by japharl** [GoogleChrome/rendertron#355]
The alpha service is currently returning a 500 error message.  Attempted to render http://serveo.net

**Comment by AVGP** [comment]
First things first: Remember that this is a demo instance, you should not rely on it but run your own instance instead.

Now, when I test that URL it works.
<img width="896" alt="Serveo__expose_local_servers_to_the_internet_using_SSH" src="https://user-images.githubusercontent.com/370246/70434363-4989e300-1a84-11ea-89c0-a62935c9d984.png">

If the issue persists, feel free to reopen this issue
