### ISSUE TITLE
refreschCache param doesnt work with Service Worker

### ISSUE THREAD

**Issue by Hexmage** [GoogleChrome/rendertron#357]
We are using a Service Worker to cache GraphQl responses for 2 hours. Sadly this has the side effect that Rendertron is using this Service Worker caching as well, even when using the refreshCache param.

I would have expected the refreshParm to also stop this from happening.

**Comment by AVGP** [comment]
Could you share a test case for this? And if you want to give fixing it a go, let me know!

**Comment by Hexmage** [comment]
@AVGP 
I have the following Scenario:
- We are using a graphql call to obtain the contents of a page. 
- We have a service-worker.js which caches the graphql call.
- Sometimes the graphql call, causes a error on fetching the data. This is now cached by Rendertron.
- Using the refreshCache=true parameter does not flush the service-worker.
- Restarting Rendertron does remove this cache.

**Comment by AVGP** [comment]
Right, sounds like there's a bunch of stuff going on.
Would you be able to reproduce this on a super simple web page that uses a service worker that loads and caches some simple data?
