### ISSUE TITLE
How do I set the flag ignoreHTTPSErrors for Puppeteer so that unsigned certificates work while developing?

### ISSUE THREAD

**Issue by redfellow** [GoogleChrome/rendertron#365]
Error: `Error: net::ERR_CERT_COMMON_NAME_INVALID at https://dev...`

Googling a bit lead me to find the `ignoreHTTPSErrors` flag that can be used with Puppeteer.connect, but I'm not sure if this can be configured in Rendertron. Any ideas?

**Comment by AVGP** [comment]
Right now there is no mechanism to pass flags into Puppeteer, but I think if you're interested in implementing that, you could extend the [Config and ConfigManager](https://github.com/GoogleChrome/rendertron/blob/master/src/config.ts) and allow a key-value pair set to pass options into Puppeteer. That would happen [here in the Rendertron code](https://github.com/GoogleChrome/rendertron/blob/0ed866fa98b31884289fcc8f2741568474a5107e/src/rendertron.ts#L32) and has the given configuration available.

**Comment by redfellow** [comment]
I found out that in headless mode the args are simply ignored. Local development workaround was to edit the `rendertron.js` to read: `const browser = await puppeteer.launch({ headless: false, ignoreHTTPSErrors: true });`

I'll be using that until I can sort out certificates in local dev env.
