### ISSUE TITLE
Rendertron cannot load JS file 1584KB.

### ISSUE THREAD

**Issue by thanhhoa214** [GoogleChrome/rendertron#367]
# Rendertron cannot load js file 1584KB ☹☹.

### Hi there, 
I'm newbie with Rendertron. My current project requires e-commerce using **[Saleor](https://saleor.io/)** and optimising SEO by **Rendertron**.

All things work well in my pet project till I integrate Rendertron into Saleor.
Saleor uses webpack bundles to an JS file just more than **1.5MB** and my **index.html** call it but **Rendertron** didn't work correctly. 
- ✔ **index.html** response didn't have any <script> (<script> run in server)
- ✔ Server didn't throw any error, not time-out, nothing.
- ✔ I tested with simple `<script>document.getElementById("root").innerHTML = "Hello World" </script>` and it runs exactly.
- ✔ I've already set *config.json* to 30000 in order to test it.
- ### ❌❌ But my data didn't exist.
## My **config.json** and **server.js**:
![image](https://user-images.githubusercontent.com/32329202/74019033-7fd2d880-49c9-11ea-8688-7a9f31b70371.png)

### * By normal user:
![image](https://user-images.githubusercontent.com/32329202/74018577-c1af4f00-49c8-11ea-8ce3-428097f9cc59.png)

### * By Googlebot:
![image](https://user-images.githubusercontent.com/32329202/74018729-f9b69200-49c8-11ea-86c1-587f5edf89a1.png)

**Comment by AVGP** [comment]
Thanks for opening a bug!

Now, I was intrigued by the notion of the size of your JavaScript breaking Rendertron.
I tried to reproduce the problem by building https://i-am-big.glitch.me/.

That test case loads 2 MB of JavaScript. Within that JavaScript it generates the content of the page. The [source code can be seen (and copied/edited) here](https://glitch.com/edit/#!/i-am-big?path=public/client.js:1:0).

That [renders just fine with Rendertron](http://render-tron.appspot.com/render/https://i-am-big.glitch.me/), so it cannot be just the size.

Could you build a publicly-accessible test case for us to investigate this further?

**Comment by thanhhoa214** [comment]
I use **ngrok** to publish it but in an other way, I cannot keep it too long.
Next time you comment I'll make it live for you.

## More clarification:
I created an git repo here: [https://github.com/thanhhoa214/demo-rendertron](https://github.com/thanhhoa214/demo-rendertron)
Now, my shortern structure:
![image](https://user-images.githubusercontent.com/32329202/74078248-7cd3f880-4a5a-11ea-916a-f1922b9206d2.png)

- ### As an user, normally, nothing to say ✔:
- ### As a bot, it's happened ❌:

>- #### When using your file **avgp.js** ✔ RUN
![image](https://user-images.githubusercontent.com/32329202/74078405-78a8da80-4a5c-11ea-9089-7b128e52c1ce.png)


>- #### When using my file **thanhhoa214.js** ❌ NOT RUN
![image](https://user-images.githubusercontent.com/32329202/74078385-4c8d5980-4a5c-11ea-8630-8d8337077722.png)

### I still research to fix it. Thank you so much for all your enthusiam 👍.

**Comment by AVGP** [comment]
I ran the demo version (also through ngrok proxy) including your thanhhoa214.js and rendertron was rendering it fine as you can see here:
![Screenshot of the rendertron output](https://user-images.githubusercontent.com/370246/76630560-88767b80-6540-11ea-8ba4-51adc00168c5.png)

Have you tried reducing the code in that file by disabling components or removing content and seeing what specific part of the code breaks the rendering output for you?

**Comment by AVGP** [comment]
I'll close this bug for now - feel free to reopen with new information.
