### ISSUE TITLE
Possible malware on the home page, render-tron.appspot.com

### ISSUE THREAD

**Issue by ehausen** [GoogleChrome/rendertron#368]
When I go render-tron.appspot.com [POSSIBLE MALLWARE BEHIND THAT URL] , which seems to be the home page for this project, my antivirus software gives this warning:

![image](https://user-images.githubusercontent.com/6204129/74349371-d6bb2200-4dbc-11ea-9831-52006b63e7da.png)

**Comment by AVGP** [comment]
Do you happen to know how to report a false positive for avast?

**Comment by AVGP** [comment]
Reported as false positive to Avast.
