### ISSUE TITLE
Clearing cache

### ISSUE THREAD

**Issue by samuelli** [GoogleChrome/rendertron#37]
Should not clear on every instance. Clearing also needs to go through every cache option.

**Comment by hekod777** [comment]
Hi

My team wants to use Rendertron to perform SSR for several of our sites.

We'd like to see an endpoint that we can hit and clear the cache for all the pages of a site. 

if we can clear a specific page on a specific site that will be even better.

Thanks!

**Comment by samuelli** [comment]
Does the endpoint need to be secure at all?

**Comment by hekod777** [comment]
We'd like to have it secured.

Anyone outside my company should not be able to use the endpoint.

We are using AWS at the moment, I'd like to know your opinion on how to implement the security.

**Comment by haihoi2** [comment]
HI, anyone here update or follow this?

**Comment by AVGP** [comment]
The fundamental function is present, but there is currently no way to get to it.
This would require a PR to set up a route to it.

I would leave the authentication out of Rendertron as that's something that is best dealt with on the level of whatever infrastructure is making the calls to Rendertron (i.e. the reverse proxy or whatever other server is in front of Rendertron)

**Comment by AVGP** [comment]
Right now, Rendertron 3.0.0 provides the `/invalidate/<url>` endpoint to remove individual URLs from a cache.
I think having an endpoint to clear the entire cache would be useful.

Are you interested in implementing this feature?

**Comment by AVGP** [comment]
This landed in 3.1.0
