### ISSUE TITLE
Rendertron rendering fine but SEO crawler showing timoeout error

### ISSUE THREAD

**Issue by pwnkumar221** [GoogleChrome/rendertron#374]
SEO crawler shows timeout error.
How to fix this issue?
I have also enabled cache but I have to fetch it again and agin in debugger to get the og tags in second time rendering as it serve cache it shows og tags but not in first fetch.

![Screenshot 2020-04-01 at 5 49 12 PM](https://user-images.githubusercontent.com/45421953/78136431-3343d080-7441-11ea-8ddd-9052aa300891.png)
![Screenshot 2020-04-01 at 5 49 20 PM](https://user-images.githubusercontent.com/45421953/78136437-350d9400-7441-11ea-90e5-6f7df378b5f5.png)
![Screenshot 2020-04-01 at 5 49 28 PM](https://user-images.githubusercontent.com/45421953/78136442-363ec100-7441-11ea-9229-961c69edff82.png)

**Comment by AVGP** [comment]
Besides making the URL faster to render, you can pre-warm the cache by requesting a renderer before you test the URL in these tools.

**Comment by pwnkumar221** [comment]
Any article on how to do the pre warm cache???

**Comment by pwnkumar221** [comment]
> Besides making the URL faster to render, you can pre-warm the cache by requesting a renderer before you test the URL in these tools.

Any article on how to do the pre warm cache???

**Comment by AVGP** [comment]
Write a script that calls rendertron for the URLs you want cached. For example:

```javascript
const fetch = require('node-fetch') 
const prewarmUrls = [
  'http://example.org/',
  'http://example.org/somepage',
  //... 
]

Promise.all(prewarmUrls.map(url => fetch('http://your-rendertron/render/' + url)).then(function() { console.log('done');}) 

```
