### ISSUE TITLE
https request results in http <base href> using express-middleware

### ISSUE THREAD

**Issue by j-heinze** [GoogleChrome/rendertron#375]
I am using the express-middleware and I am sending a request with LinkedInBot as User-Agent via Postman to my domain with https as protocol. This results in rendertron being called with a non-https-Url. Due to this the `<base href>` in the html is also a non-https-URL. This results in a mixed-content error in various browsers.  

The problem must be within my express setup or the rendertron-middleware. I veriefied the rendertron instance returns the right `<base href>` if renderton.appspot.com/render/https://mydomain.test gets called. 

`    const incomingUrl =
      req.protocol + '://' + req.get('host') + req.originalUrl;
`

Should work though. If anyone has an idea what could be causing this, I would really appreciate it.

**Comment by j-heinze** [comment]
Okay,

apparently I was behind a proxy and hat to enable trust-proxy in my express settings. Sorry, for that.

**Comment by nethanjan** [comment]
Hi @j-heinze Please can you explain this?

**Comment by StanBondar** [comment]
@j-heinze, can you explain please in more detail how have you solved this problem? What was the value for trust-proxy in express settings or how have you used this: `const incomingUrl = req.protocol + '://' + req.get('host') + req.originalUrl;`? 
Thank you in advance!
