### ISSUE TITLE
Question: Sitemap generating

### ISSUE THREAD

**Issue by AlexMachin-Xercise4Less** [GoogleChrome/rendertron#376]
Hi,

For my companies site were using Rendertron, so far it has worked wonders, it helped us at a critical time in December. However, we need to be able to generate a sitemap. 

Does Rendertron support this functionality? It discovers all 400+ pages, surely it can output all the pages to an XML file which we can upload somewhere.

I'm just looking for a solution, since were using Rendertron I thought I could ask here 👍 

Thanks,

Alex

**Comment by AVGP** [comment]
Rendertron doesn't discover sites, it just passes through requests, really.
Depending on your setup (CMS, framework, ..) there will likely be better options.
Also, with a couple hundred pages, sitemaps aren't that useful to Google anyway.
