### ISSUE TITLE
HTML DOCTYPE declaration being stripped

### ISSUE THREAD

**Issue by git-ekuo** [GoogleChrome/rendertron#378]
First of all, thank you for the great project! It saved me a lot of time in making my website crawler-ready.

#### The issue I'd like to report
I believe Rendertron is stripping out HTML DocType declaration in our responses. While it's fine for some crawlers, it's doesn't work so well with some crawlers like Facebook sharing debuggers. May I know if there is a way for rendertron to keep the doctype declaration in outputs? 
 
A quick example to reproduce what I meant. 

a **regular** GET request to https://www.google.com returns the following: 

```
<!DOCTYPE html>
<html itemscope="" itemtype="http://schema.org/WebPage" lang="en-HK" class="wf-nunitosans-n4-active wf-active"><head><meta charset="UTF-8"><meta content="origin" name="referrer">

... Remaining removed for brevity
```

However, a **rendertron** GET request via https://render-tron.appspot.com/render/https://www.google.com returns the following:
```
<html itemscope="" itemtype="http://schema.org/WebPage" lang="en" class="wf-nunitosans-n4-active wf-active"><head><base href="https://www.google.com"><meta charset="UTF-8"><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description">
 
... Remaining removed for brevity
```

I checked through the code, and saw this line:

`const result = await page.evaluate('document.firstElementChild.outerHTML') as string;`

I believe this is where doctype declaration was removed. May I know if it's possible for us to have a config or option to keep the doctype declaration in rendertron output? 

Thank you!

**Comment by AVGP** [comment]
Hey @git-ekuo thanks for reporting this! As far as I can tell, that is a shortcut we took when getting the DOM content and we should fix this. Would you be interested in giving it a go and trying to fix this? I'm happy to help with this.

Anyway, for anyone who wants to give this a go, we should:

1. Create a test case that fails (render a simple HTML file and check if the doctype is present in the result) and a test case that renders something that does not have a doctype, to make sure we're not breaking that scenario.
2. Find a way to get the doctype into the rendered HTML as well. We could check if a doctype is present and then try to reconstruct it, for example.

**Comment by git-ekuo** [comment]
Hi @AVGP , 

No problem. Sure! I will give it a go. Will ask for your help if I cannot get it working.

**Comment by AVGP** [comment]
Thanks, that's awesome! Let me know if you get stuck or need a pull request review :)

**Comment by git-ekuo** [comment]
Hi @AVGP , 

Not sure if you saw my Pull Request, I finished the change. I had trouble passing one of the cache tests. I believe it's not related to my change. Can you give me a hand on that? I checked through the builds, it seemed that you already are trying to resolve it already. Thanks!

**Comment by AVGP** [comment]
Hey @git-ekuo - thanks for the quick turnaround on the pull request! I'll take a look this week and I think the failing test is a flaky test that we are dealing with anyway, so it should be good to go :)

**Comment by AVGP** [comment]
#379 is merged :)
