### ISSUE TITLE
Fix the refreshCache tests

### ISSUE THREAD

**Issue by AVGP** [GoogleChrome/rendertron#381]
Both the tests for refreshCache with dataStore and with memoryCache seem to be incorrect.
They are also flaky, so we need to rethink and rewrite them.

**Comment by git-ekuo** [comment]
Hey @AVGP , I am keen to take this on to see if I can have it fixed. Can you assign it to me? I will try to have both test scenarios fixed.

Just my initial thoughts on the issue. Please let me know if it's incorrect.

- Value test on the `refreshCallCount` variable shall be removed. We should test directly that cache (content) is refreshed when `refreshCache=true` is passed in the URL.

**Comment by AVGP** [comment]
This issue is all yours :) I think you are right - when I re-read the test case, I wasn't sure about this either. I think it would be a cleaner test if it would directly test the cache interface (and thus the cache's content and behaviour).
