### ISSUE TITLE
How do I see where rendertron is spending it's time

### ISSUE THREAD

**Issue by jackmoore** [GoogleChrome/rendertron#382]
It takes rendertron about 2 seconds to render my test, which is much more than my expectation / budget. How do I debug or log this so that I can inspect where it's spending it's time?

**Comment by AVGP** [comment]
Rendertron itself is a pretty thin layer wrapping around [puppeteer](https://pptr.dev/) which in turn is just a client to [Chrome Devtools protocol](https://chromedevtools.github.io/devtools-protocol/). I expect most of the time is probably spent in Chrome starting up and getting ready to take commands via CDP.

You can use 

- [Node.js profiling](https://nodejs.org/en/docs/guides/simple-profiling/) to see where Rendertron / Puppeteer spends its time, 
- run chrome in non-headless (see below) to watch how the page gets rendered and/or 
- use the [User Timing API](https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API) to see where in your page the time gets spend.

My guess is that most of the two seconds is spend starting Chromium.
To be able to observe what Chromium is doing, you can configure Rendertron to run Chrome in non-headless mode. To do so, change [this line](https://github.com/GoogleChrome/rendertron/blob/6fd7f253ecf829c3dcd2a348e0f101758f1bf1c4/src/rendertron.ts#L26) in `rendertron.ts` from:

```javascript
const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
```
to this code:

```javascript
const browser = await puppeteer.launch({ headless: false, args: ['--no-sandbox'] });
```
and then build Rendertron on your local machine (`npm run build`) and run it locally with `npm start`.
