### ISSUE TITLE
Harmonize memory cache and datastore cache

### ISSUE THREAD

**Issue by AVGP** [GoogleChrome/rendertron#383]
Currently, the memory cache implementation (unlike the datastore cache) limits the number of entries, but does not have an expiry timer for individual entries, risking that an entry stays cached indefinitely (or until cache is purged / Rendertron is restarted).

Meanwhile, the datastore cache has an expiry timer but no way of specifying a maximum number of entries in the cache, making it possible to increase the cache size indefinitely.

The goal of this issue is to harmonize behaviour by:

1. Add a max number of cache entries to datastore-cache, similar to what memory-cache does
2. Add an expiry time for cache entries in memory-cache, similar to what datastore-cache does

**Comment by dwsmart** [comment]
I would be interested in taking this one on

**Comment by ashleyish** [comment]
^^I'll tag team with Dave!

**Comment by AVGP** [comment]
That's awesome, thanks so much @ashleyish and @dwsmart for taking this on :)

**Comment by dwsmart** [comment]
I think it's correct to handle the new `filesystem-cache` in the same way too if possible?

**Comment by AVGP** [comment]
@dwsmart That's correct - ideally all caches would behave the same way.

**Comment by AVGP** [comment]
Thanks so much for landing this!
