### ISSUE TITLE
Host and Port defined in config.json are ignored

### ISSUE THREAD

**Issue by richardhofmaenner** [GoogleChrome/rendertron#385]
Hi all,

I think I've found a small bug with the host and port config. If you specify the port and/or the host within the config.json in the root directory these two settings wont be used by the server.

**Example**
Inside the config.json I have the following settings:
`{ "port": "2001", "host": "127.0.0.1"}`

After starting the rendertron the server is listening on the default host and port.

![image](https://user-images.githubusercontent.com/8899885/80825340-762fca00-8be0-11ea-86a9-40f78556eb12.png)
Logging the config object after the assignment of host/port inside the Rendertron initialize-function.

If you like, I can make a PR with a fix for this.

Cheers,
Richard

**Comment by AVGP** [comment]
Hey @richardhofmaenner Thanks for reporting this! It'd be super great if you would submit a PR fixing this :) Thank you for your support!
