### ISSUE TITLE
TravisCI is failing

### ISSUE THREAD

**Issue by odanado** [GoogleChrome/rendertron#387]
The following error occurs when the `cd middleware && npm run lint && npm run test` command is executed.

```bash
node_modules/ava/index.d.ts:5:10 - error TS2339: Property 'observable' does not exist on type 'SymbolConstructor'.
5  [Symbol.observable](): ObservableLike;
```

This error has been reported in an issue of `ava`. 
https://github.com/avajs/ava/issues/2212

And, the error has been solved in version 3.0 of ava.
https://github.com/avajs/ava/pull/2308

There are three options for resolving this error.

- add `"skipLibCheck": true` in `middleware/tsconfig.json`
- explicitly install version 12.x.y of `@types/node`
- upgrate ava to version 3

What do you think about these three options?

**Comment by AVGP** [comment]
I think it's time to update ava.

**Comment by odanado** [comment]
Do you have plans and work planned for the update?
If you don't have a plan, I will like to work on it.

**Comment by AVGP** [comment]
Go for it, @odanado!
