### ISSUE TITLE
Expand configuration docs

### ISSUE THREAD

**Issue by AVGP** [GoogleChrome/rendertron#390]
The configuration documentation ([this file](https://github.com/GoogleChrome/rendertron/blob/master/docs/configure.md) is a copy and paste from the README.

It would be nice to extend it a little bit, especially:

- there is another cache provider "filesystem" that isn't mentioned yet
- the options could be grouped (e.g. `width` & `height` as "Layout" or "viewport", `host` & `port` under "Server settings", etc.)
- Check in [the ConfigManager](https://github.com/GoogleChrome/rendertron/blob/master/src/config.ts) if there are undocumented options
- Explain what the timeout means in more detail

**Comment by richardhofmaenner** [comment]
Hi @AVGP 

I would like to take this and try my first time on docs ;)

**Comment by AVGP** [comment]
Awesome, go for it, @richardhofmaenner

**Comment by AVGP** [comment]
@richardhofmaenner Any updates? Anything I can do to get you started? :)
