### ISSUE TITLE
Desktop Rendering a blank page using rendertron

### ISSUE THREAD

**Issue by umangnaik** [GoogleChrome/rendertron#404]
in our angular application, the first page is rendering blank in desktop only with mobile it working fine.
couple a month ago we have changed the structure of our site will it may affect it?...because before release new layout it working well with both desktop and mobile 
I have tried with a timeout but with angular, it seems meaningless to use a timeout...
please help me...

**Comment by AVGP** [comment]
Without a sample URL, there isn't much we can do here.
The fact that it used to work and continues to work with mobile settings suggests that this is a problem in your Angular app, not Rendertron.

If you have more details (especially if you can reproduce this with a URL that you can share with us), feel free to re-open this issue.

**Comment by umangnaik** [comment]
Hello
        Below are our live site URL https://right-on.co.jp/
currently, we have resolved our PC & sp conflict HTML CSS code
so we can able to get mobile code in desktop but still we are far away from
mobile view in google cached & desktop view in google cached

seems code site issue in it.
currency only a few views are rendered in google cached pages..
maybe due to the lazy loading component ??
can you please help me ...

**Comment by AVGP** [comment]
Don't use Google Cache to draw conclusions. I would recommend using the [mobile-friendly test](https://g.co/mobilefriendly) and look at the rendered HTML there. It does look like some of the content didn't load, you can investigate more there.
Also: bit.ly/js-sites-wg is a mailing list where you can check if someone else has an idea on this.
