### ISSUE TITLE
Publish new npm version?

### ISSUE THREAD

**Issue by pleerock** [GoogleChrome/rendertron#405]
rendertron on npm is two years old. Features specified in README and multiple bugfixes and memory leak fixes aren't available on npm. Maybe its time to publish a new version?

**Comment by AVGP** [comment]
We have a bunch of backwards-compatibility breaking changes lined up for a 3.0.0 release soon. I expect that to happen sometime in June.

**Comment by AVGP** [comment]
Happy to announce that **3.0.0** has just been released 🎉
