### ISSUE TITLE
strip module scripts

### ISSUE THREAD

**Issue by maxisam** [GoogleChrome/rendertron#406]
https://github.com/GoogleChrome/rendertron/blob/04ed0fc6755135d83e3cfa6472d1134d3c05ffa1/src/renderer.ts#L39-L45

Is there any reason we don't strip script with type="module" ?

For angular 8+, it will general 2 differential builds. https://angular.io/guide/deployment#differential-builds

Is it possible to have strip type as an option?

Thanks!

**Comment by AVGP** [comment]
That's because modules weren't thought of when that was written. I think it doesn't need to be an option, but it should be part of the default behavior. Do you want to write a test and add that behavior there?
