### ISSUE TITLE
Filesystem cache not working on Ubuntu

### ISSUE THREAD

**Issue by art2limit** [GoogleChrome/rendertron#414]
my config.json:

```
{
    "cache": "filesystem",
    "cacheConfig": {
    "cacheDurationMinutes": 72000,
    "cacheMaxEntries": 10000,
    "snapshotDir": "/home/username/rendertron/cache"
    },
    "timeout": 60000
}
```

command to start `sudo bin/rendertron`
system: `Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)`

there are no logs on command line about failure, just every same response take ~5 secs to respond and there are not folder or files on snapshotDir

**Comment by art2limit** [comment]
`npm install & npm update` and start via `npm run start` also don't changed situation

**Comment by AVGP** [comment]
The file system csche is a feature that isn't on npm yet. Soon we will publish version 3.0 but for now, you will have to install Rendertron from Github for this to work - see https://docs.npmjs.com/cli/install
