### ISSUE TITLE
Can we passing additional parameter from rendertron server 

### ISSUE THREAD

**Issue by umangnaik** [GoogleChrome/rendertron#417]
this is my domain of rendertron server
http://52.196.33.254:3000
when i fetch below URL of our site
/https://xyz.com
so the request should be following
http://52.196.33.254:3000/render/https://xyz.com

i need to append static additional parameter like **?rt=true**
it should look like following always
http://52.196.33.254:3000/render/https://xyz.com?rt=true

where rt=true is always there for any request with above rendertron request

**Comment by AVGP** [comment]
You can do this by [URL encoding](https://en.wikipedia.org/wiki/Percent-encoding) the parameters.

For your example, the render URL would be: http://52.196.33.254:3000/render/https://xyz.com%3Frt%3Dtrue
