### ISSUE TITLE
Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by art2limit** [GoogleChrome/rendertron#423]
We use rendertron at production and after 2 weeks of rendering, rendertron infinitely began to produce an error:
```
rendertron.service - Instance to serve rendertron
   Loaded: loaded (/etc/systemd/system/rendertron.service; disabled; vendor preset: disabled)
   Active: failed (Result: core-dump)

rendertron: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
rendertron: 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [rendertron]
```
Restarting rendetron service solved problem, but it looks like for a while

config.json:
```
{
"host":"127.0.0.1",
"port":4000,

"cache": "memory",
"cacheConfig": {
"cacheDurationMinutes": 72000,
"cacheMaxEntries": -1,
"snapshotDir": "/var/www/rendertron/website-cache/"
    },
"timeout":30000
}
```

looks like increase the `node` memory will solve this problem, how we should do that?

**Comment by dwsmart** [comment]
From your config.json file, you are allowing unlimited amounts of pages to be cached in memory, with them living for 50 days, so if you have a large site, they could really stack up in memory and cause the issues you are seeing.

When you restart rendertron, all cache is purged if you are using the memory cache like in your configuration. 

From what I remember node has a 1.7GB (or something like that) limit in memory, but I believe you can increase it.

Personally I'd question if that's a good way to do it and explore if the filesystem cache would be better for you, but if you really need to use the memory cache, I'd look at setting a `cacheMaxEntries` value to stop this happening.

**Comment by dwsmart** [comment]
The config file you have above uses memory:
change "cache": "memory", to "cache": **"filesystem",** if you want to use that.

You shouldn't need to add pupeeterArgs ? Are you getting an error somewhere about that? 

```javascript
{
"host":"127.0.0.1",
"port":4000,
"cache": "filesystem",
"cacheConfig": {
"cacheDurationMinutes": 72000,
"cacheMaxEntries": -1,
"snapshotDir": "/var/www/rendertron/website-cache/"
    },
"timeout":30000,
"pupeeterArgs": ["--no-sandbox"]
}
```
would set the pupeeterArgs the same as the default though. and use the filesystem cache.

**Comment by art2limit** [comment]
yep i understand that, thank you :)

but question about how increase node-js heap through rendertron config.json, if we add to `pupeeterArgs` `--max-old-space-size=4096` it's will works?

**Comment by dwsmart** [comment]
No,

`pupeeterArgs` is for passing the args array over to puppetter, [see puppetter docs](https://pptr.dev/#?product=Puppeteer&version=v3.0.0&show=api-puppeteerdefaultargsoptionsl) these are basically [chromium command line switches](https://peter.sh/experiments/chromium-command-line-switches/)

You would need to increase the memory in node using that flag, not puppeteer.

**Comment by art2limit** [comment]
this is our service config:

```
[Unit]
Description=Instance to serve rendertron
After=network.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/var/www/rendertron
Environment="PATH=/usr/local/bin:/usr/bin"
ExecStart=/usr/bin/node --max-old-space-size=4096 /var/www/rendertron/bin/rendertron

[Install]
WantedBy=multi-user.target
```

everything work fine now, thanks :)
