### ISSUE TITLE
Get CSS used to render the page 

### ISSUE THREAD

**Issue by anuragphadke** [GoogleChrome/rendertron#424]
Hi,
Is there a way to get CSS that was used to render a given output'ed by Rendertron? 

Alternatively, I can use puppeteer to get CSS coverage, just wondering if Rendertron has any out of box config.

**Comment by AVGP** [comment]
This isn't something within the scope of Rendertron, but puppeteer might be
able to answer this question.

**Comment by AVGP** [comment]
FWIW, Puppeteer has coverage - https://pptr.dev/#?product=Puppeteer&version=v3.3.0&show=api-class-coverage

**Comment by anuragphadke** [comment]
thx @AVGP . I will give that a try.
