### ISSUE TITLE
Flutter page is not rendered correctly

### ISSUE THREAD

**Issue by sotisoti** [GoogleChrome/rendertron#425]
Does it support flutter rendering?

https://gallery.flutter.dev/

**Comment by dwsmart** [comment]
Hey @sotisoti, I took a quick look at this too out of interest, renderton seems to render most of the content ok, but it does trip up if you view the output in a browser, that mostly seems to be down to that example page using images with [blob:](https://developer.mozilla.org/en-US/docs/Web/API/Blob) which won't show cross domain.

I guess if you aren't too bothered about them, say you're dynamic rendering for bots, it might not be too big an issue?

**Comment by AVGP** [comment]
Closing this for lack of interactions. Please feel free to reopen if this continues to be a problem and you're interested in working together on a solution :)
