### ISSUE TITLE
Modify build/renderer.js file

### ISSUE THREAD

**Issue by umangnaik** [GoogleChrome/rendertron#427]
Hello Folks ,
         I want to change the renderer.js file content which includes in the build folder.
i want to add additional query parameter that add boolean true or false 
i have achieved my goal but if i used npm run build then my changes are overwritten with default so I want to permanently fix that issue in my website .
temporary without npm run build i am working 
please help me how can i do this,
if i clone project that not include any build folder

**Comment by AVGP** [comment]
If you modify the src/renderer.ts file instead, it will be built and run by npm.

**Comment by umangnaik** [comment]
Thank you its working
