### ISSUE TITLE
filesystem_cache: bug with removing from cache.

### ISSUE THREAD

**Issue by hheexx** [GoogleChrome/rendertron#430]
I have problem that there is unrealistic number of "removing cache: 94becf484da4d7090db064c319db900d.json" entries being logged. Looks like a loop may be off.

**Comment by hheexx** [comment]
I just found out it is looping over same files as it's not deleting them. For some reason deleting silently failes.

**Comment by AVGP** [comment]
Could this be a permission issue on your host?

**Comment by hheexx** [comment]
It could be, I will check tomorrow.
Anyway silently failing is not nice.

**Comment by AVGP** [comment]
That's true. If you want to investigate that and maybe make a pull request for better error logging, I think [this part of the code](https://github.com/GoogleChrome/rendertron/blob/main/src/filesystem-cache.ts#L69) is the place to look for.

**Comment by dwsmart** [comment]
Hey @hheexx 

If you don't fancy tackling this I am happy to take it on.

Out of interest, what OS are you hosting rendertron on? I initially had issues on Windows hosts, but that seemed fine after changing to `fs.unlinkSync` but perhaps it doesn't fully solve the issue?

**Comment by hheexx** [comment]
@dwsmart sure! I have no direct experience with node.

I'm on Linux in Docker.

**Comment by dwsmart** [comment]
Hi,

Found a bug, looks like the function that cleared out old caches when the max number of entries had been reached was leading to an extra `.json` being appended to the filename to be deleted, it failed silently here, as the file with the double .json didn't exist, no attempt was made to delete.

**Comment by hheexx** [comment]
Awesome! Thanks!

**Comment by AVGP** [comment]
Thanks, @dwsmart! 🎉

**Comment by hheexx** [comment]
I confirm fixed!
