### ISSUE TITLE
Rendertron static serving for Facebook, Twitter Crawl

### ISSUE THREAD

**Issue by ThanhNguyen101-acazia** [GoogleChrome/rendertron#437]
Hi everyone, 

I have been trying to serve static rendering with the proper meta tags for the last few days.

Rendertron rendered and serialized all the meta tags we added with react-helmet, however, for some reasons Facebook scrappers did not pick up the meta tags.

This is the command that we used:

`curl -v --compressed -H "Range: bytes=0-524288" -H "Connection: close" -A "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)" https://apicafe.io/`

The above command returns results that we expected.

However, running the Facebook scrapper from the debug console returns none of our expected metadata:

`https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fapicafe.io%2F`

Apparently it was cut off by the size of the massive inline stylings? How should we resolve this?

Thank you all and have a good day.

**Comment by AVGP** [comment]
That's a great question for Facebook's developer support. As Rendertron produces the relevant HTML, I would report an error via their support options.

**Comment by ThanhNguyen101-acazia** [comment]
Hi @AVGP , do you see anything unusual from my curl above?

**Comment by AVGP** [comment]
Nothing unusual. I tried via Chrome with the relevant UA from the FB bot, too - all good.
I don't know why Facebook's scraper doesn't see the full HTML - and it's not the first time that people struggle with their scraper in general. 

As the issue isn't on our end, I don't know what to do with this, unfortunately.

**Comment by ThanhNguyen101-acazia** [comment]
Thanks you for answering me.

**Comment by ThanhNguyen101-acazia** [comment]
@AVGP I've just fix the issue. The problem come from the my end. Because of fetch a lot of style inline css and it's take much time and size to load them so facebook and twitter can't crawl the meta tag after <style> tag. Just minimize them and it's will work

**Comment by AVGP** [comment]
Interesting. So FB / Twitter have very short timeouts, I guess?

**Comment by ThanhNguyen101-acazia** [comment]
Yes, With following of document of FB, it's required all meta tag must render before the request exceed 1MB.
