### ISSUE TITLE
websocket firebase connection timeouts

### ISSUE THREAD

**Issue by raDiesle** [GoogleChrome/rendertron#443]
v3.0.0

I figured out, that trying to render page with fetching Firestore data in browser does not work and fails with timeout.
I want to get /screenshot from page.

Code to fetch data with React.js :
`
 firestore.db.collection("decks")
        .get()
        .then((documentSnapshots) => {
...
`

There is not error in console, other than "timeout"

Any idea how I can resolve problem?

**Comment by raDiesle** [comment]
Duplicate of #110

**Comment by raDiesle** [comment]
I see code is expected to be merged in master branch, but the feature does not exists. https://github.com/GoogleChrome/rendertron/commit/a0552fb75cf1e8495f85b0d33b7744bb89acea2a

also "FAQ Auto detecting loading function" indicates such functionality, but it seems it does not exist.

**Comment by AVGP** [comment]
Hey @raDiesle - thanks for reporting!

Let me address three things coming up in this thread:

1. The outdated FaQ section
2. The explicit render event
3. Issues with Firebase's Firestore

1.) The outdated FaQ section
You're right that the "Auto detecting loading function" isn't part of Rendertron - it was phased out before I took over the project, so I can't comment much on that, but will definitely update the FaQ section.

2.) The explicit render event
Regarding the explicit render - would you like to see such feature in Rendertron in the future?
The feature hasn't made it into mainline and there seems to be a low amount of demand here as far as I can see..

3.) Firebase Firestore issues
I do have a question regarding the issue you describe with Firebase and Firestore.
I've set up the [quickstart demo app](https://github.com/firebase/quickstart-js/tree/master/firestore) and rendered it through Rendertron without issues. Can you give us a minimal reproduction example that shows the problem?

**Comment by raDiesle** [comment]
Hi @AVGP thanks for your support.

I setup https://github.com/firebase/quickstart-js/tree/master/firestore example and it has same issue of timeout.
Which example you tried?

**Comment by AVGP** [comment]
Interesting - seems to render fine here: http://render-tron.appspot.com/render/https://task2-b4c26.web.app/

**Comment by AVGP** [comment]
I can't reproduce the problem, neither locally nor on the demo instance of Rendertron.

Feel free to update it with more information and reopen the issue!

**Comment by vesper8** [comment]
@AVGP I would like to see an explicit render event added. In some cases my page is fully loaded long before the 10 second mark but Rendertron continues to wait, triggering the timeout.. I believe this is possibly because of ads that cause the browser to think the page hasn't finished loading. I would like to be able to explicitly say that the page is done loading after some API calls have been done.

I would also like to know if there's a way to detect if the page is being loaded by Rendertron, in which case I would simply not load any ads
