### ISSUE TITLE
Only first render request works, rest return 400

### ISSUE THREAD

**Issue by dwsmart** [GoogleChrome/rendertron#486]
I cloned the main branch, ran `npm install`, then `npm run build`. After this I started the instance with `npm run start`

A call to `http://localhost:3000/render/https://example.com/` works as expected, but any further render request, (no matter what the url requested to render) returns a 400 (with `response does not exist` returned in the console).

I have tried this on both windows 10, and an unbuntu 18 box, same thing.

Any clues anyone?

**Comment by dwsmart** [comment]
Hi,

Some further digging, it appears to be this:

https://github.com/GoogleChrome/rendertron/blob/78492cc325a4022f2de27a1bbb0c84806afdd498/src/renderer.ts#L101-L109

Interception seems like it [might cause issues with puppeteer](https://github.com/puppeteer/puppeteer/issues/631) in this respect. 

It this seems to have been added in #476

**Comment by dwsmart** [comment]
More specifically, it's just https://github.com/GoogleChrome/rendertron/blob/78492cc325a4022f2de27a1bbb0c84806afdd498/src/renderer.ts#L101

With that commented out, everything runs perfectly as far as I can tell, but not sure exactly how important that is to interception on the page listener on Lines 103 - 109 ?

**Comment by AVGP** [comment]
Quick question: Can you reproduce that with a version from github.com/avgp/rendertron on branch release-3.1.0?

**Comment by dwsmart** [comment]
@AVGP this is weird, it seems to work now on most sites (both that branch and main), so I assume there's something specific to the ones that fail... Odd, it appears to be sites built in sapper. (not that you would use rendertron on them anyway I guess...)

Sorry if I've wasted time here.

**Comment by AVGP** [comment]
No, this is interesting. I think it'd be interesting to see what about
sapper sites breaks rendertron as there's a chance we've got a general
blind spot somewhere then...

Dave Smart <notifications@github.com> schrieb am Do., 22. Okt. 2020, 17:21:

**Comment by dwsmart** [comment]
This appears to be something with puppeteer itself, will investigate more and open an issue over there.

**Comment by pvo13** [comment]
I see the same faulty behavior on my Ionic 5/angular app. The first render request works, all other fail with 400.

**Comment by dwsmart** [comment]
Interesting @pvo13 looks like it's not JUST sapper. I can recreate this issue straight in puppeteer puppeteer/puppeteer#6541, the only reliable way around it I have found so far is to close the browser ( browser.close() ) and reopen it each time, but that seems like it would potentially have performance impact.

**Comment by dwsmart** [comment]
fixed with #502

**Comment by pvo13** [comment]
@dwsmart Works for me, thank you.

**Comment by sunnyuff** [comment]
{ "closeBrowser" : true }
works for me for rendertron@3.1.0
