### ISSUE TITLE
Renderton processes do not seem to terminate

### ISSUE THREAD

**Issue by marek99** [GoogleChrome/rendertron#494]
After running the rendertron for a couple of days, I have several dozen of its processes eating up server resources:
```
root      2086  0.0  0.1 4763004 39344 ?       Sl   Oct22   0:00 /srv/renderton/git/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome --type=renderer --no-sandbox --al
root      2234  0.0  0.1 4763004 36428 ?       Sl   Oct22   0:00 /srv/renderton/git/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome --type=renderer --no-sandbox --al
```
have I overlooked some parameter in the configuration, or is this maybe a known issue?

**Comment by AVGP** [comment]
It looks like Chromium isn't removing its renderer child processes.
This might be addressed with #502 so keep an eye on that :)

**Comment by AVGP** [comment]
Did you try it with Rendertron 3.1.0 and the new (optional) `closeBrowser` config flag set to true?

**Comment by marek99** [comment]
ok, deployed the 3.1.0, will see how it works ;)

**Comment by AVGP** [comment]
@marek99 Any news? :)

**Comment by marek99** [comment]
Seems fine by now. Five chrome processes running (four of them since last deployment).

**Comment by AVGP** [comment]
Alright, thanks for the feedback! I'll close this bug for the moment, feel free to reopen if this issue reappears!
