### ISSUE TITLE
render-tron.appspot.com is up to date?

### ISSUE THREAD

**Issue by abdonrd** [GoogleChrome/rendertron#526]
https://render-tron.appspot.com is up to date?

If not, maybe we can add a GitHub Action to deploy the `master` branch:

https://github.com/google-github-actions/setup-gcloud/tree/master/appengine-deploy

**Comment by AVGP** [comment]
I just updated the demo instance, thanks for pointing this out.
The problem I am running into with the automated deployment is that I can't set up a service account key.
After having been investigating why, it seems that the organisation-level policy disables this - so I can't get the GH action to work as I have no means of authentication in the CI environment.
