### ISSUE TITLE
Backend is being ignored when render page

### ISSUE THREAD

**Issue by thanhdn1989** [GoogleChrome/rendertron#539]
I have this page:
https://udv.arter.dk/taxa/taxon/details/926eddf8-f785-ea11-aa77-501ac539d1ea
Which meta tag will be updated after successfully getting information from Back end

I've try using the demo page: https://render-tron.appspot.com/render/https://udv.arter.dk/taxa/taxon/details/926eddf8-f785-ea11-aa77-501ac539d1ea
And using Facebook sharer: https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Frender-tron.appspot.com%2Frender%2Fhttps%3A%2F%2Fudv.arter.dk%2Ftaxa%2Ftaxon%2Fdetails%2F926eddf8-f785-ea11-aa77-501ac539d1ea

But it result in the meta tag's new value is ignored
My spec:
+ Angular 9
+ Hosted in Azure app service

**Comment by dwsmart** [comment]
Hi @thanhdn1989 

I think you are just hitting the 10 second timeout limit, (that's certainly happening when I test it using a local build of renderton.

I do see some updating of open graph tags sometimes, but I think you are just running out of time.

**Comment by AVGP** [comment]
Hey there, as Dave said - it's likely a timeout issue.
Also note that Facebooks opengraph debugging tool behaves a little odd sometimes.

As the demo URL no longer seems to have the meta tags you mentioned, I'm closing this issue for now.
Feel free to reopen if there's anything to add or for us to look into.
