### ISSUE TITLE
cacheKey includes '/render/' in url, causing invalidate to not remove entry from store

### ISSUE THREAD

**Issue by abertramds** [GoogleChrome/rendertron#558]
When a url is rendered, the cacheKey that is being stored includes the '/render/' from the url path, causing the invalidate endpoint to not remove the url.

I am sure there is a more graceful patch but locally, simply removing '/render/' when defining the cacheKey, has fixed this for me.
`const cacheKey = ctx.url.replace('/render/', '');`

I am using the 'memory' option as my cache.

**Comment by AVGP** [comment]
Will roll out with 3.2.0
