### ISSUE TITLE
Ionic 5 / Angular pages are not rendered correctly

### ISSUE THREAD

**Issue by pvo13** [GoogleChrome/rendertron#586]
I played around with the shadowDom parameters but rendertron never renders the pages correctly. On the other hand, the snapshot parameter works fine and I see a picture of a correctly rendered page.

Here is a link to an example app that shows the same issue:

https://ionic5-starter-tutorial.firebaseapp.com/home
https://github.com/ionicthemes/ionic5-starter-app-tutorial

**Comment by pvo13** [comment]
I guess it has something to do with shadow DOM and polyfills, but I am a noob regarding this. Other info I found points into that direction. e.g.
https://stackoverflow.com/questions/58838982/ionic-4-rendertron-not-rendering-web-components

**Comment by AVGP** [comment]
It's likely to be similar to #484 the root cause being compatibility issues with Shadow DOM v1

**Comment by pvo13** [comment]
What I see is that the content of my pages are correct, but the styling is totally off or non-existing. You can see what I mean if you access my website with a browser whose user agent is set to Googlebot. You might need to reload it a few times.

[https://sportsdate.app/en/activities](url)
