### ISSUE TITLE
[Docs] Add health check URL to API docs

### ISSUE THREAD

**Issue by AVGP** [GoogleChrome/rendertron#595]
Add the health check endpoint to [the API reference](https://github.com/GoogleChrome/rendertron/blob/main/docs/api-reference.md) and maybe the [README.md](https://github.com/GoogleChrome/rendertron/blob/main/README.md).

The URL is `/_ah/health`, it takes no parameters and will respond with HTTP 200 and the text "OK", if the Rendertron server is healthy.

**Comment by ShrillShrestha** [comment]
Hi @AVGP, I am new to open source, and am looking to learn and contribute. This issue seems a good opportunity for me to do that. If you can guide me, maybe I can solve it.

**Comment by AVGP** [comment]
That's awesome news, @ShrillShrestha!

I'm very happy to help :) A first good step is to check out [this guide on how to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/).

You can actually do most of the necessary steps right from your browser:

1. Click "Fork" on the top right corner to get your own fork of this project.
2. In your own fork in your browser, navigate to the `docs/api-reference.md` file and click on the edit button (pen symbol).
3. Make the edits (add a new section, like the other existing sections).
4. Save the change and make sure it says "Create new branch".
6. Go to the main repository (this one here), click "Pull requests" and it should suggest to open a pull request from the new branch you created when saving the edit. 

Let me know if you have further questions!

**Comment by ShrillShrestha** [comment]
Sure @AVGP, I will try to work on it. If I have any questions, I will let you know.

**Comment by ShrillShrestha** [comment]
@AVGP, so the files that to be changed is only `api-reference.md`?

**Comment by AVGP** [comment]
Thank you, @ShrillShrestha - your change has now been merged and you're now a Rendertron contributor! 🎉

**Comment by ShrillShrestha** [comment]
Thanks, @AVGP for helping me out. I am happy to contribute. :)
