### ISSUE TITLE
This page isn’t working

### ISSUE THREAD

**Issue by shivaprasad87** [GoogleChrome/rendertron#602]
working fine with facebook.com url, but not with all websites, PFA
![Screenshot from 2021-02-02 17-23-08](https://user-images.githubusercontent.com/38426537/106596830-8dd71d00-657b-11eb-8837-26da52822467.png)

**Comment by AVGP** [comment]
I can't reproduce the issue either on the demo instance, nor a local Rendertron server based on the latest main branch.
Can you reproduce the issue and share the necessary steps with us?

**Comment by AVGP** [comment]
Due to a lack of sufficient information, I'm closing this. Should you have additional information for us or can reproduce the issue, let us know and/or reopen this issue.
