### ISSUE TITLE
App Engine pricing

### ISSUE THREAD

**Issue by silenceisgolden** [GoogleChrome/rendertron#65]
With the current settings in the app.yaml config, it looks like the cost for App Engine on this project would be a minimum of $452/month. If I am a user looking to solve SEO for my blog that is hosted for almost nothing on Firebase, I could imagine there being quite a shock when all of my GCP free credits are used up in two thirds of a month.

1. Are the App Engine resource definitions a strong recommendation from the maintainers?
2. (If my math is correct) Could a warning be added in the README to caution casual projects from blindly deploying this and forgetting about it?

The math (https://cloud.google.com/appengine/pricing#flexible-environment-instances)

Assumptions
* App engine flex does not scale to 0.
* I still remember how to math.
* The pricing in the above link is correct.

Avg hours in a month = 730
vCPU = $0.0526 / core / hour
Mem = $0.0071 / GB / hour

8 vCPU and 28 GB of memory

$0.0526 * 730 * 8 = $307.184
$0.0071 * 730 * 28 = $145.124
$307.184 + $145.124 = ~$452 / month

**Comment by samuelli** [comment]
Hi,

I've updated the default resource recommendations. For something like a blog, you are welcome to use the demo endpoint as well. See updated readme.

Let me know if that's insufficient.

Thanks.
