### ISSUE TITLE
Add Koa middleware

### ISSUE THREAD

**Issue by glen-84** [GoogleChrome/rendertron#664]
It would be great if Rendertron included Koa middleware.

I understand that it's not practical to include middleware for every available framework, but Rendertron just so happens to depend on [multiple Koa packages](https://github.com/GoogleChrome/rendertron/blob/6f681688737846b28754fbfdf5db173846a826df/package.json#L38-L44) anyway, so it seems like it would be a good fit.

**Comment by AVGP** [comment]
I think now is a good time to retire the express middleware and move to koa. Would you be interested in doing that?

**Comment by glen-84** [comment]
@AVGP,

I'm in the process of writing Koa middleware, so I might be able to contribute that here.

I had started using Axios instead of the deprecated `request`, because I thought that `node-fetch` only supported timeouts using the [awkward AbortController](https://www.npmjs.com/package/node-fetch#request-cancellation-with-abortsignal), but I see now (in your PR and in the docs), that there is in fact a `timeout` option, even though it does state "Signal is recommended instead". Do you still prefer `node-fetch`? (see also https://github.com/node-fetch/node-fetch/issues/523#issuecomment-438158003)

I'm not sure about _replacing_ the Express middleware though, as there are many users using that framework (as dead as it appears to be). That's obviously your call though.

**Comment by glen-84** [comment]
@AVGP Do you have a moment to respond to the questions above? 🙂

**Comment by glen-84** [comment]
[Koa middleware for Rendertron (using Axios)](https://gist.github.com/glen-84/4ad04cab7ed3ec74a2e6ed04e6c12348).

Usage:

```ts
app.use(
    makeMiddleware({
        proxyUrl: "http://my-rendertron-instance/render"
    })
);
```

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
