### ISSUE TITLE
Can't download resource with relative path 

### ISSUE THREAD

**Issue by HermanZzz** [GoogleChrome/rendertron#669]
Example: https://render-tron.appspot.com/render/https://www.monsterhunter.com/rise/cn/

**Comment by HermanZzz** [comment]
For Example.
![image](https://user-images.githubusercontent.com/8086434/115179659-67e70080-a106-11eb-946d-bfef87597fc8.png)
The original url is "https://www.monsterhunter.com/rise/assets/images/logo.png".
But loaded as "https://www.monsterhunter.com/assets/images/logo.png"

**Comment by HermanZzz** [comment]
![image](https://user-images.githubusercontent.com/8086434/115179877-e80d6600-a106-11eb-870d-a230965d0a60.png)
![image](https://user-images.githubusercontent.com/8086434/115179853-db890d80-a106-11eb-897e-ea8773d367dc.png)

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
