### ISSUE TITLE
Add `Discordbot` to `botUserAgents`

### ISSUE THREAD

**Issue by glen-84** [GoogleChrome/rendertron#671]
Slackbot, TelegramBot, and WhatsApp are included – any reason not to include Discordbot?

I guess there's a limit to how many user agents should be included by default. How do you decide which ones to include?

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
