### ISSUE TITLE
Question about scaling and race conditions

### ISSUE THREAD

**Issue by rudolfbyker** [GoogleChrome/rendertron#690]
Is running multiple Rendertron containers (e.g. AWS ECS) with a shared filesystem (e.g. AWS EFS) cache vulnerable to race conditions? Or is this supported?

**Comment by gravi2** [comment]
@rudolfbyker I am having similar setup and so far have not seen issues based on some internal issues only. This is yet to go to production, so can't comment much. 
I would expect the EFS to be slower but have not benchmarked. So share your findings.

**Comment by rudolfbyker** [comment]
Thanks! I'm also Considering using the far gate "bind mount", which is
faster, but ephemeral. But then the same question about race conditions
needs to be answered. I will report back later if and when I know whether
my setup works. :)

**Comment by gravi2** [comment]
Are you using rendertron on AWS fargate? I did read few articles where
people setup puppeteer on AWS fargate and AWS lambda. But was wondering if
rendertron performance will be lower on fargate compared to bare EC2
instances.

**Comment by rudolfbyker** [comment]
Yes, I'm running Rendertron on AWS ECS with the "Fargate" launch type.
Seems to work fine.

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
