### ISSUE TITLE
Document API call to drop the entire cache

### ISSUE THREAD

**Issue by rudolfbyker** [GoogleChrome/rendertron#691]
It would be very useful to have an API call to drop the entire cache. I would like to do that when deploying a new version of the app, because on every build, all JS and CSS files get new names (build hash), and the cached HTML in rendertron will still try to load the old JS files, resulting in a broken page. When a JS-aware bot hits such a page, it will fail to execute the JS.

**Comment by dwsmart** [comment]
Hey @rudolfbyker 

There is an API endpoint for this already, looks like it's not documented.

```
GET /invalidate
```

So basically the same as the documented api to remove a specific url, just without the `/<url>` bit

**Comment by rudolfbyker** [comment]
Does the `/invalidate` endpoint also work with some kind of wildcard?

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
