### ISSUE TITLE
Document that Rendertron is not supposed to be run with untrusted web data

### ISSUE THREAD

**Issue by AVGP** [GoogleChrome/rendertron#697]
Rendertron should be configured with an allow-list and behind a reverse proxy, rather than exposed to the open internet.

This should be reflected in the readme as well as the documentation.

**Comment by Patil2099** [comment]
I would love to submit a pr for this.

**Comment by FrenchConectionkevinpare** [comment]
________________________@hellsAngelfaitevraimenttuertousnorthsiderzeetapresvoussiegererauxparlement

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
