### ISSUE TITLE
Mobile query param not toggling, seems to be sticky

### ISSUE THREAD

**Issue by jlafosse** [GoogleChrome/rendertron#702]
The mobile query param seems to be sticky somehow. For example, if I start up a new instance of rendertron without any caching enabled and pass the ?mobile onto the end of the url, the target page will render as mobile correctly. However if I then remove the ?mobile and refresh the page it is still mobile. In fact if I hit any other url they will all be rendered as mobile. If I stop the server and restart and then hit the pages without ?mobile they will show as desktop, however now the opposite occurs in that if you add ?mobile onto the urls they still will not render as mobile until the server is restarted.

I am using rendertron v3.1.0 and here is my config:

```
{
    "puppeteerArgs":[
        "--disable-web-security",
        "--no-sandbox",
        "--disable-setuid-sandbox"
    ],
    "port":"3000",
}
```

Any help would be appreciated... thanks.

**Comment by jlafosse** [comment]
Ok so apparently if I add `closeBrowser:true` to my config it solves the issue... although I am unsure if this is expected behavior.

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
