### ISSUE TITLE
In the output what do the ms and kb stand for and why are these different for googlebot?

### ISSUE THREAD

**Issue by mikeooi** [GoogleChrome/rendertron#721]
When I hit my rendertron service and render a page in the rendertron console output I get: 

200  70ms 716.78kb

But when the same URL is hit by googlebot I get the output:

200 1,831ms 26.09kb

To help diagnose if I there is a problem, what do these figure represent, and why are they different for googlebot?

Thanks!

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
