### ISSUE TITLE
Rendertron Lambda function

### ISSUE THREAD

**Issue by Zukqurnain** [GoogleChrome/rendertron#722]
Can we deploy this code in lambda function using server less koa?
https://www.npmjs.com/package/aws-serverless-koa

**Comment by Nabeel-Zafar** [comment]
Yes we can @Zukqurnain

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
