### ISSUE TITLE
Does googlebot factor in response times from rendertron in it's ranking calculation?

### ISSUE THREAD

**Issue by mikeooi** [GoogleChrome/rendertron#727]
Is googlebot aware of when it's receiving a prerendered response and therefore doesn't rely on these response times in its ranking algorithm?

Due to my setup, I'm currently getting a response time of 1-4 seconds for cached pages and 3-11 seconds for pages that are being rendered on the fly, and if google is using these load times in it's ranking calculation then I have a problem.

**Comment by AVGP** [comment]
mikeooi ***@***.***> schrieb am Fr., 18. Juni 2021, 17:44:

> Is googlebot aware of when it's receiving a prerendered response and
> therefore doesn't rely on these response times in its ranking algorithm?
>
No it doesn't.


Due to my setup, I'm currently getting a response time of 1-4 seconds for
> cached pages and 3-11 seconds for pages that are being rendered on the fly.
>

That, however, has a potential impact as pagespeed and crawl rate might be
affected.

**Comment by mikeooi** [comment]
Thanks!

(I'm not bothered about crawl rate since the content doesn't change often) but if these lengthy response times affect googlebots calculation of page speed, doesn't this mean this will affect ranking since page speed is used in the ranking calculation?

**Comment by mikeooi** [comment]
I got the answer from prerender.io - they say google uses analytics data to calculate page speed so using dynamic rendering does not affect googles calculation of page speed and therefore ranking

**Comment by dwsmart** [comment]
@mikeooi , just a clarification on this, Google gathers performance data from the [The Chrome User Experience Report](https://developers.google.com/web/tools/chrome-user-experience-report) 

This is independent from analytics, but yes it is the experience users would have on the site, not what googlebot would see
