### ISSUE TITLE
Enable to configure any Koa.js middleware

### ISSUE THREAD

**Issue by hatappi** [GoogleChrome/rendertron#735]
## Background
In the current rendertron implementation, when it starts, Koa.js middlewares below are configured.
https://github.com/GoogleChrome/rendertron/blob/main/src/rendertron.ts#L44-L48

But each developer can't add any Koa.js middleware and configure any options to existing Koa.js middleware.

For example in my use-case, I'd like to output JSON format log but currently, rendertron configures [koa-logger](https://github.com/koajs/logger).
It doesn't support JSON format, so I'd like to use [bunyan-logger](https://github.com/koajs/bunyan-logger) or [cabinjs](https://cabinjs.com/) instead of koa-logger

## Expected behavior
Developer can configure any Koa middlewares instead of existing middlewares

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
