### ISSUE TITLE
Missing Emojis and Japanese Characters

### ISSUE THREAD

**Issue by patrick91** [GoogleChrome/rendertron#74]
Hello! 

I was trying the screenshot demo with my website, and I noticed that it doesn't show emojis,
I've made a quick bin here: http://jsbin.com/qakokocihe

As you can see from the [screenshot](https://render-tron.appspot.com/screenshot/http://jsbin.com/qakokocihe?width=2300&height=1222) it is not rendering the Emojis and the Japanese Characters. 

This is probably because it is missing the relative fonts.

**Comment by joelgriffith** [comment]
I'm working on a small SaaS product that will handle things like this. Instead of exposing certain endpoints for rendering, generating HTML, or any specific case you'll instead have access to a running chrome instance in the cloud and can talk to it with your favorite library (chromeless, puppeteer, selenium, whatever). Fixes other numerous issues as well other than Asian characters missing.

Is this something that you'd be interested in?

**Comment by dickeylth** [comment]
As where as other Asia Characters such as Chinese.

**Comment by samuelli** [comment]
Hi,

Thanks for the report. I'll look into fixing this. It is worth nothing though, that this only affects the screenshot endpoint. It does not affect SEO since the correct serializations should still be sent.

**Comment by GautierT** [comment]
@samuelli : Hi, any news on this problem ? Is this a font issue ? Thanks

**Comment by joelgriffith** [comment]
This is definitely a font issue, you'll have to pull in/install more packages in your dockerfile and potentially use a different base image. Googl's Noto font line-up has been my goto

**Comment by GautierT** [comment]
I'm using heroku. Any idea or direction to help me with that? Thanks a lot.

**Comment by joelgriffith** [comment]
In docker, this roughly looks like:

```
wget https://github.com/emojione/emojione-assets/releases/download/3.1.2/emojione-android.ttf && fc-cache -f -v
```

Here I'm using the emojione font to render emoji's properly. I'm not super familiar with Heroku, so you'll have to refer to their documentation on how to add assets to a box. Finally, if this is something that you'd rather not deal with entirely, I'm working on a service that is custom built for headless chrome [here](https://browserless.io). Fonts and emoji's are one thing it aims to solve without fuss.

**Comment by GautierT** [comment]
@joelgriffith  :  thanks ! But doesn't work. I think i have to first remove dejavu font because after installing emojione it's still dejavu font who are used. Your service is very interesting but too expensive for me now... :/

**Comment by chemitaxis** [comment]
Hi! Is this issue solved? Any ideas? Thanks!

**Comment by nollytainment** [comment]
> Hi! Is this issue solved? Any ideas? Thanks!

Also stuck here man! nothing seem to be working

**Comment by aftoncreative** [comment]
@nollytainment have you tried with the latest puppeteer version?

I had exactly the same problem. I added 'emojione-android.ttf'-font to my ubuntu-server. My emojis were blurry and had skin tone balls next to emojis.

When i updated to the lastest puppeteer-version, the problem was fixed.

**Comment by AVGP** [comment]
This isn't an issue with Rendertron, but with the environment configuration.

For example, it works here:
![image](https://user-images.githubusercontent.com/370246/64573420-8fb0a700-d3ae-11e9-9f69-497140bd7064.png)

The demo instance fails with Emojis, but displays the other text.

We no longer officially support the Docker deployment and setting up the fonts depends on the environment, not on Rendertron, so I'm closing this.
