### ISSUE TITLE
Question about initialize Rendertron class ourselves

### ISSUE THREAD

**Issue by hatappi** [GoogleChrome/rendertron#741]
If I read the README.md, I can run Rendertron excuting `rendertron` or `npm run start`.
https://github.com/GoogleChrome/rendertron/tree/6f681688737846b28754fbfdf5db173846a826df

Is it not recommended to use Rendertron class directly to our application?

For example:

```node
import { Rendertron } from "rendertron";

const rendertron = new Rendertron();
rendertron.app.on("error", (err, ctx) => {
   // something error handling
});

rendertron.initialize();
```

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
