### ISSUE TITLE
Migrate to Puppeteer

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/rendertron#75]
https://github.com/GoogleChrome/puppeteer provides high level APIs for working with headless Chrome. Lot of rendertron's underlying code could be simplified (even removed) by adopting the puppeteer API.

**Comment by joelgriffith** [comment]
I was kind of shocked to not see it in `deps`!

**Comment by ebidel** [comment]
Think @samuelli started this long before Puppeteer was a thing :)

**Comment by samuelli** [comment]
Yup, definitely started this earlier :)

I did chat to Andrey though and I'm not sure about I could implement everything using Puppeteer. Is there an escape hatch to the protocol if I use Puppeteer?

**Comment by ebidel** [comment]
Coming: https://github.com/GoogleChrome/puppeteer/issues/31

**Comment by samuelli** [comment]
Yup, definitely need that @ebidel!

**Comment by ebidel** [comment]
Looks like someone created a clone that uses puppeteer: https://github.com/cheeaun/puppetron

**Comment by mrtristan** [comment]
not sure on priority level for something like this but if you guys haven't noticed that prereq mentioned above is now merged in on the pupeteer side!

**Comment by samuelli** [comment]
Done.
