### ISSUE TITLE
I want to run a cloud function to dynamically render

### ISSUE THREAD

**Issue by 34r7h** [GoogleChrome/rendertron#750]
Some devs  are saying it's not possible to run Rendertron directly in a cloud function but this post explains how to run puppeteer in a cloud function - https://rominirani.com/using-puppeteer-in-google-cloud-functions-809a14856e14

Is there a reason we must run a separate instance for rendertron to work? If so, can we sequence separate methods instead?

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
