### ISSUE TITLE
Make waitUntil a config driven option

### ISSUE THREAD

**Issue by fabiangarga** [GoogleChrome/rendertron#754]
In some cases users will want to change the `waitUntil` configuration from puppeteer to avoid timeouts with firebase sockets or related open connection that might be left in some type of applications.

It would a very easy enhancement, and in my case would solve a timeout issue with Rendertron.
There should be no point to keeping this configuration as a hardcoded value on the app.

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
