### ISSUE TITLE
Script monitor-inspect points to non existing file src/main.js

### ISSUE THREAD

**Issue by hos** [GoogleChrome/rendertron#765]
It seems that `monitor-inspect` script not working as expected. I found that `nodemon` command trying to run file `src/main.js` [here](https://github.com/GoogleChrome/rendertron/blob/main/package.json#L22) which seems does not exist.
Locally I was able to fix it by changing  command to `nodemon -x "node --inspect build/rendertron.js"`, if this is write let know so I will open PR for this.

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
