### ISSUE TITLE
Add address without protocol

### ISSUE THREAD

**Issue by rajikaimal** [GoogleChrome/rendertron#77]
Adding an address without protocol gives 
Eg : google.com
`Cannot render google.com - "First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object."`

Maybe support for building the URL from the address provided ?

**Comment by samuelli** [comment]
This is just in the UI right?

**Comment by rajikaimal** [comment]
Yeah, I tested only the UI, shall I work on this ?

**Comment by samuelli** [comment]
A PR would be great!

**Comment by rajikaimal** [comment]
I'll work on this
