### ISSUE TITLE
the memory of chrome process keeps increasing

### ISSUE THREAD

**Issue by baiyonghong1989** [GoogleChrome/rendertron#771]
hello,I've recently been using rendertron as a solution for our seo. 
   I found that after I started rendertron, even if there were no crawler requests, there were still some chrome process that were resident. And the number of processes varies in different environments :in dev environment, the number of chrome process is 5 when the server is idle，while in prod environment the number is 98。
  and my config of rendertron is below:
{
  "cache": "filesystem",
  "cacheConfig": {
    "cacheDurationMinutes": "10080",
    "cacheMaxEntries": "50000",
    "snapshotDir":"/renderCache"
  },
  "timeout": 5000,
  "closeBrowser": false
}
  
 In addition, I find that in the production environment, the chrome process ID does not change, and the memory usage of these processes keeps increasing.  Even in the server is idle, the memory usage of the resident chrome process does not decrease。
   And when the  memory usage of all Chrome processes exceed about 70 percent of the server's memory , all chrome processes will be killed at a time ，and i do not know who does it 。Most importantly,  I want to  know  why the memory usage hasn't decreased when there are no crawler requests .
   thanks very much . and this is the first time i create issue in github,The description may not be clear, please forgive me

ps: rendertron version:3.1.0    chromium stable version: 85.0.4183.83

**Comment by tdierolf** [comment]
Any news on this? We are facing the same issue.

Example (rendering one page each 15 minutes):
![grafik](https://user-images.githubusercontent.com/10610201/165723178-7db47abd-dfc4-4b8e-8bef-c5c58f80920f.png)

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
