### ISSUE TITLE
Password protection / authentication

### ISSUE THREAD

**Issue by rudolfbyker** [GoogleChrome/rendertron#783]
This is a feature request. Could we have some form of authentication or password protection? This would help in the situation where you need to expose a private Rendertron instance to the internet so that your CI can call e.g. the `invalidate` endpoint after deployment.

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
