### ISSUE TITLE
restrictedUrlPattern does not exist in the latest published npm package 3.1.0

### ISSUE THREAD

**Issue by jbuckner** [GoogleChrome/rendertron#792]
I noticed `restrictedUrlPattern` was added in [this PR](https://github.com/GoogleChrome/rendertron/pull/525), but it has not been released yet to npm. Could you release this feature?

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
