### ISSUE TITLE
Question: What is the reason of cutting pathname in rendertron which is used in <base>  as a page default URL 

### ISSUE THREAD

**Issue by vcernomschi** [GoogleChrome/rendertron#811]
Could you please help to understand why rendertron cuts page URL which is used in <base> tag  as a page default URL ?

Reference: https://github.com/GoogleChrome/rendertron/blob/main/src/renderer.ts#L226

I ams asking as it leads to invalid behaviour when crawler tries to check empty link defined as `<a href="#">Empty link URL</a>`. 

For example, potentially for the following URL: "https://developer.mozilla.org/en-US/docs/Web/API/URL" it will add the following base tag (which in my specific case leads to "Not Found" resource):

`<base href="https://developer.mozilla.org/en-US/docs/Web/API">`

Just wondering if it is only applied for use case when the pathname ends with slash "/".

**Comment by chimame** [comment]
I'm having the same issue.

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
