### ISSUE TITLE
cant get rendertron to work.

### ISSUE THREAD

**Issue by strid3r21** [GoogleChrome/rendertron#848]
maybe I'm doing something wrong, i dont know. but ive got rendertron deployed to GCP and running. it works if i go to the https://garden-manager-20781.appspot.com and put my domains url into the field and hit submit. but when i run my domain through google search console it still doesn't render the JS.

here is the code for rendertron thats deployed to GCP.

`const express = require('express');
const app = express();
const rendertron = require('rendertron-middleware');

const BOTS = rendertron.botUserAgents.concat('googlebot');
const BOT_UA_PATTERN = new RegExp(BOTS.join('|'), 'i');

app.use(
  rendertron.makeMiddleware({
    proxyUrl: 'https://garden-manager-20781.appspot.com/render',
    userAgentPattern: BOT_UA_PATTERN,
  })
);`

my domain name is www.viewplants.com which is hosted on firebase under the same project id being used above for the rendertron.

my project is built in VUEjs. 

am i missing something?

**Comment by danielmintz** [comment]
Same problem. did you find a fix?
