### ISSUE TITLE
using rendertron with php and prerender.io middleware.

### ISSUE THREAD

**Issue by hekod777** [GoogleChrome/rendertron#89]
Hello

My ultimate goal is to use rendertron with PHP.

and I saw this in readme

> Rendertron is also compatible with prerender.io middleware.

I have tried to use prerender middleware for expessJS. 

`app.use(require('prerender-node').set('prerenderServiceUrl', 'http://localhost:3000/render'));`

but it just couldn't reach the rendertron end point.

I'd like to know if I can use prerender middleware for Zend Framework to get rendertron work with PHP. If so, what is needed to get this done?

also I'd like to know the minimum version of Node and Express required by rendertron. (in the readme is saying node 7+, but I read somewhere people are saying 7.60+ is needed.)

Thank you!

**Comment by mccreadylemon** [comment]
For Apache I do it like this:

```
RewriteEngine On
RewriteCond %{ENV:PROXY} !true
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{HTTP_USER_AGENT} (google|bot|spider|pinterest|crawler|archiver|flipboardproxy|mediapartners|facebookexternalhit|insights|quora|whatsapp|slurp) [NC,OR]
RewriteCond %{HTTP:from} .+
RewriteRule .* - [E=PROXY:true,E=REQUEST_PATH:%{REQUEST_URI}]

RewriteCond %{ENV:PROXY} true
RewriteRule ^(.*)$ http://127.0.0.1:3000/render/https://%{HTTP_HOST}%{REQUEST_URI} [P,QSA,L]
```
hope this helps!
