### ISSUE TITLE
Add timeout options for screenshots

### ISSUE THREAD

**Issue by mcorbe** [GoogleChrome/rendertron#902]
For Digital Signage purposes, we have HTML Creatives that changes after `domcontentloaded` in order to make sure we never display black or loading screens. We do not build these Creatives and cannot optimize the code / makes sure the content is fully painted before `domcontentloaded` event.

We would like to add a timeout option around the `page.screenshot(...)` puppetteer call so that we can ensure our screenshots are taken at the right time.

Here is an issue from puppeteer github with a proposed solution:

https://github.com/puppeteer/puppeteer/issues/2117

Happy to create an MR if that helps.

**Comment by ForbiddenEra** [comment]
Hi,

I think that perhaps there's some misunderstanding here. While having a timeout for *taking* a screenshot is great, this can easily be implemented on the developers side.

The original issue that I think people were asking for a fix for, was a timeout for if the screenshot fails/doesn't return within a certain period.

**Comment by ForbiddenEra** [comment]
Also should mention that for your particular issue, you can wait for a specific element to be available, this is for example what we do on a page where content is loaded dynamically (a form) where we need to enter data.

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
