### ISSUE TITLE
about googlebot

### ISSUE THREAD

**Issue by hekod777** [GoogleChrome/rendertron#91]
Everyone is saying that googlebot has no problem clawing polymer 2.0 websites.

according to polymer-project.org, it seems like a true statement.

I deployed a very simple polymer 2.0 app on heroku using express to serve the index.html.

and try to use google console to fetch the page.

Sadly, the result didn't show anything inside the shadow dom.

and currently googlebot is not on the user agent list.

Maybe we should add googlebot to the user agent list for rendertron middleware as well?

**Comment by samuelli** [comment]
Hi,

Please ensure you are using `webcomponent-loader.js` in your application for googlebot.

**Comment by hekod777** [comment]
Hi Sam

the app was built using polymer cli and has webcomponents-load.js in index.html.

this is the result of google bot fetching

```
<body>
    <my-app></my-app>
    <h1>ABC</h1>
</body>
```

there is nothing inside my-app tag.

if rendertron can have an option to add google bot to the list, then it will make it easier to test things out.

**Comment by samuelli** [comment]
What version of webcomponentsjs are you using?

**Comment by hekod777** [comment]
the version of webcomponentsjs is 1.0.8

**Comment by samuelli** [comment]
There was an issue in 1.0.8. Please use 1.0.7 or >= 1.0.9.

**Comment by hekod777** [comment]
OK thank you very much!

**Comment by hekod777** [comment]
hmmm

bower.json is now

`"webcomponentsjs": "webcomponents/webcomponentsjs#^1.0.9"`

but still getting the same result.

everything between `my-app` tag is ignore by google bot

**Comment by samuelli** [comment]
Are you serving ES5?

**Comment by hekod777** [comment]
yes ES5.

now google bots can render the stuff!

Thank you very much!

PS: any luck on rendering Angular 4 apps using polymer 2.0 web components?

**Comment by samuelli** [comment]
Great, I mentioned to your colleague that we really need more detail to look into that issue. Reproduction steps, minimized test cases would be really helpful.
