### ISSUE TITLE
Push to Docker Hub

### ISSUE THREAD

**Issue by klausenbusk** [GoogleChrome/rendertron#93]
Instant of everyone need to build the image, it could be useful if we could just pull the image from Docker Hub or some other Docker Registry (quay? Google Cloud Registry?)

**Comment by samuelli** [comment]
Hi,

I have pushed it to https://hub.docker.com/r/samdotli/rendertron/ but I need to figure out how to properly push a repository instead. Also any idea on how I can get to be an unnamed one?

**Comment by samuelli** [comment]
I'll look into Google Cloud Registry as well.

**Comment by ravishivt** [comment]
With 2.0.0, it feels like the project is making backward progress to support users who want to use docker.  Why not publish a docker image that is built by installing puppeteer and rendertron?  It would be simpler for users than cloning the repo and building rendertron natively. 

I've also opened a request for puppeteer to publishes their images, https://github.com/GoogleChrome/puppeteer/issues/3072.  When/if that is done, the Dockerfile for rendertron would be simple:

```Dockerfile
FROM puppeteer:latest

WORKDIR /home/pptruser
ENV WORKDIR /home/pptruser

COPY . .

RUN npm install || \
  ((if [ -f npm-debug.log ]; then \
      cat npm-debug.log; \
    fi) && false)

RUN npm run build

ENTRYPOINT [ "npm" ]
CMD ["run", "start"]
```

It'll be a little ugly to have puppeteer build logic + rednertron build logic but until puppeteer publishes their images, I think the result is worth it.
