### ISSUE TITLE
problem with metadata

### ISSUE THREAD

**Issue by cyber-goka** [GoogleChrome/rendertron#948]
hello whenever I'm sharing content in messengers or social platforms there is default image and description. problem is whenever the URL is encrypted like https://delta.staging.watchchoice.tv/en/playlists%3Fplaylist%3D6593d80e-3ca4-4e62-a3bd-63cbee4c3ef6 so it is working with metadata but this URL will not work it is 404 and normal URL like https://delta.staging.watchchoice.tv/en/playlists?playlist=6593d80e-3ca4-4e62-a3bd-63cbee4c3ef6 are not working

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
