### ISSUE TITLE
Benchmark result

### ISSUE THREAD

**Issue by jasonslyvia** [GoogleChrome/rendertron#95]
First of all, I really appreciate your excellent work! 

We've been thinking building a similar screenshot service after Chrome Headless come out, glad we found rendertron before we start developing our own.

The thing is, we intend to use this screenshot/render service in production environment but couldn't find any benchmark result or pressure test result, like how many screenshot requests can it take parallelly? 

Do you have any plan doing this, how can we help out?

**Comment by joelgriffith** [comment]
Benchmarking is pretty tough for something like screenshots (and there's a number of other factors in play depending on _where_ you host the image). In cases like AWS' IoT/lambda infrastructure there's roughly a ~2 second delay waiting for the function to run + loading the image.

That said, I've generally found that you can run around 10 parallel screenshot requests on a fairly common VM (1GB ram, 1 CPU) and expect them to finish in a few seconds.

I've also generally found it's better to scale horizontally than vertically, as Chrome does what it will with resources. So, it's generally favorable to launch a few images and then load-balance them (which is what I've done at browserless.io)
