### ISSUE TITLE
Not working for deep pages

### ISSUE THREAD

**Issue by aaryavrate** [GoogleChrome/rendertron#988]
Has anyone faced this issue?
https://stackoverflow.com/questions/73904944/rendertron-middleware-not-rendering-anything-other-than-root-page

My rendering works for base URL only. Others give 504 error.

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
