### ISSUE TITLE
https://render-tron.appspot.com/ is down

### ISSUE THREAD

**Issue by jcblancomartinez** [GoogleChrome/rendertron#990]
Hi,

Having https://render-tron.appspot.com/ to try out the product was great.

Unfortunately, https://render-tron.appspot.com/ is down.

Could you please get it up again or point us to a different URL where we can play with Rendertron?

Thanks.

Best Regards.

**Comment by jcblancomartinez** [comment]
Hi @addyosmani 

Could you please help with this?

Thank you.

**Comment by AVGP** [comment]
Hey! The demo instance will no longer be provided.
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
